### ISSUE TITLE
Latest CLI version breaks storage localhost

### ISSUE THREAD

**Issue by mosnicholas** [supabase/cli#1108]
# Bug report
I've upgraded to Supabase v1.61.0 locally. When I try and access `http://localhost:54323/project/default/storage/buckets`, I get an error (in the screenshot below). When I try and create buckets, I get an error too `new row violates row-level security policy`.

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## To Reproduce
1. Upgrade to 1.61.0
3. Go to storage buckets in the localhost CLI
5. You'll see an Internal Server Error
6. Try and create a bucket, you'll see another error

## Expected behavior
It should work like before

## Screenshots
![image](https://github.com/supabase/cli/assets/3606778/6fc9f589-4d8d-4f34-bb58-96487a7897f0)

## System information

- OS: macOS
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

## Additional context
```
2023-05-16 08:59:38 {"level":"info","time":"2023-05-16T15:59:38.874Z","pid":1,"hostname":"782b6ac87ad5","reqId":"req-bb","tenantId":"stub","project":"stub","msg":"content-type is application/vnd.openxmlformats-officedocument.wordprocessingml.document"}
2023-05-16 08:59:16     at /app/node_modules/knex/lib/execution/internal/query-executioner.js:46:12
2023-05-16 08:59:16     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-05-16 08:59:16     at async Runner.ensureConnection (/app/node_modules/knex/lib/execution/runner.js:300:14) {
2023-05-16 08:59:16   statusCode: 403,
2023-05-16 08:59:16   error: 'Unauthorized',
2023-05-16 08:59:16   originalError: error: 
2023-05-16 08:59:16           SELECT
2023-05-16 08:59:16             set_config('role', $1, true),
2023-05-16 08:59:16             set_config('request.jwt.claim.role', $2, true),
2023-05-16 08:59:16             set_config('request.jwt', $3, true),
2023-05-16 08:59:16             set_config('request.jwt.claim.sub', $4, true),
2023-05-16 08:59:16             set_config('request.jwt.claims', $5, true),
2023-05-16 08:59:16             set_config('request.headers', $6, true),
2023-05-16 08:59:16             set_config('request.method', $7, true),
2023-05-16 08:59:16             set_config('request.path', $8, true);
2023-05-16 08:59:16        - permission denied to set role "service_role"
2023-05-16 08:59:16       at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)
2023-05-16 08:59:16       at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)
2023-05-16 08:59:16       at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)
2023-05-16 08:59:16       at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)
2023-05-16 08:59:16       at Socket.emit (node:events:513:28)
2023-05-16 08:59:16       at Socket.emit (node:domain:489:12)
2023-05-16 08:59:16       at addChunk (node:internal/streams/readable:324:12)
2023-05-16 08:59:16       at readableAddChunk (node:internal/streams/readable:297:9)
2023-05-16 08:59:16       at Readable.push (node:internal/streams/readable:234:10)
2023-05-16 08:59:16       at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
2023-05-16 08:59:16     length: 110,
2023-05-16 08:59:16     severity: 'ERROR',
2023-05-16 08:59:16     code: '42501',
2023-05-16 08:59:16     detail: undefined,
2023-05-16 08:59:16     hint: undefined,
2023-05-16 08:59:16     position: undefined,
2023-05-16 08:59:16     internalPosition: undefined,
2023-05-16 08:59:16     internalQuery: undefined,
2023-05-16 08:59:16     where: undefined,
2023-05-16 08:59:16     schema: undefined,
2023-05-16 08:59:16     table: undefined,
2023-05-16 08:59:16     column: undefined,
2023-05-16 08:59:16     dataType: undefined,
2023-05-16 08:59:16     constraint: undefined,
2023-05-16 08:59:16     file: 'guc.c',
2023-05-16 08:59:16     line: '11978',
2023-05-16 08:59:16     routine: 'call_string_check_hook'
2023-05-16 08:59:16   },
2023-05-16 08:59:16   metadata: undefined
2023-05-16 08:59:16 }
2023-05-16 08:59:38 DBError: new row violates row-level security policy
2023-05-16 08:59:38     at DBError.fromDBError (/app/dist/storage/database/knex.js:416:16)
2023-05-16 08:59:38     at Function.<anonymous> (/app/dist/storage/database/knex.js:351:31)
2023-05-16 08:59:38     at Function.emit (node:events:513:28)
2023-05-16 08:59:38     at Function.emit (node:domain:489:12)
2023-05-16 08:59:38     at Client_PG.<anonymous> (/app/node_modules/knex/lib/knex-builder/make-knex.js:299:10)
2023-05-16 08:59:38     at Client_PG.emit (node:events:525:35)
2023-05-16 08:59:38     at Client_PG.emit (node:domain:489:12)
2023-05-16 08:59:38     at /app/node_modules/knex/lib/execution/internal/query-executioner.js:46:12
2023-05-16 08:59:38     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-05-16 08:59:38     at async Runner.ensureConnection (/app/node_modules/knex/lib/execution/runner.js:300:14) {
2023-05-16 08:59:38   statusCode: 403,
2023-05-16 08:59:38   error: 'Unauthorized',
2023-05-16 08:59:38   originalError: error: 
2023-05-16 08:59:38           SELECT
2023-05-16 08:59:38             set_config('role', $1, true),
2023-05-16 08:59:38             set_config('request.jwt.claim.role', $2, true),
2023-05-16 08:59:38             set_config('request.jwt', $3, true),
2023-05-16 08:59:38             set_config('request.jwt.claim.sub', $4, true),
2023-05-16 08:59:38             set_config('request.jwt.claims', $5, true),
2023-05-16 08:59:38             set_config('request.headers', $6, true),
2023-05-16 08:59:38             set_config('request.method', $7, true),
2023-05-16 08:59:38             set_config('request.path', $8, true);
2023-05-16 08:59:38        - permission denied to set role "service_role"
2023-05-16 08:59:38       at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)
2023-05-16 08:59:38       at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)
2023-05-16 08:59:38       at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)
2023-05-16 08:59:38       at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)
2023-05-16 08:59:38       at Socket.emit (node:events:513:28)
2023-05-16 08:59:38       at Socket.emit (node:domain:489:12)
2023-05-16 08:59:38       at addChunk (node:internal/streams/readable:324:12)
2023-05-16 08:59:38       at readableAddChunk (node:internal/streams/readable:297:9)
2023-05-16 08:59:38       at Readable.push (node:internal/streams/readable:234:10)
2023-05-16 08:59:38       at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
2023-05-16 08:59:38     length: 110,
2023-05-16 08:59:38     severity: 'ERROR',
2023-05-16 08:59:38     code: '42501',
2023-05-16 08:59:38     detail: undefined,
2023-05-16 08:59:38     hint: undefined,
2023-05-16 08:59:38     position: undefined,
2023-05-16 08:59:38     internalPosition: undefined,
2023-05-16 08:59:38     internalQuery: undefined,
2023-05-16 08:59:38     where: undefined,
2023-05-16 08:59:38     schema: undefined,
2023-05-16 08:59:38     table: undefined,
2023-05-16 08:59:38     column: undefined,
2023-05-16 08:59:38     dataType: undefined,
2023-05-16 08:59:38     constraint: undefined,
2023-05-16 08:59:38     file: 'guc.c',
2023-05-16 08:59:38     line: '11978',
2023-05-16 08:59:38     routine: 'call_string_check_hook'
2023-05-16 08:59:38   },
2023-05-16 08:59:38   metadata: undefined
2023-05-16 08:59:38 }
```

These are the logs I see in docker

**Comment by mosnicholas** [comment]
that indeed fixed it, thank you @sweatybridge -- it seems there were some storage files that weren't getting cleaned up when I ran `supabase stop` and it caused errors with policy checks, thank you!
