### ISSUE TITLE
Enable IP version specification for realtime

### ISSUE THREAD

**Issue by Silur** [supabase/cli#1198]
https://github.com/supabase/realtime/pull/253 got merged into the upstream realtime container and works as expected if local development is happening purely in a docker-compose file but as the CLI does not support the `REALTIME_IP_VERSION` setting, having ipv6 disabled on a local system results in `supabase start` crashing the realtime component

A solution would be to add:
```toml
[realtime]
ip_version="ipv4"
```

Support for the __config.toml__ file

**Comment by sweatybridge** [comment]
This should be possible now with `npx supabase@beta start`

```
[realtime]
enabled = true
ip_version = "IPv4"
```

**Comment by Silur** [comment]
any news on this?

**Comment by sweatybridge** [comment]
@Silur are you still running into the same error? CLI now defaults to IPv4 because docker support for IPv6 is not very good.

**Comment by Silur** [comment]
yes the issue still persists on latest cli versions when ipv6 is disabled

**Comment by lolcabanon** [comment]
I still get this problem today with CLI v2.26.9.

I have this in my `config.toml` :

```toml
[realtime]
enabled = true
ip_version = "IPv4"
```

Running `pnpx supabase start --debug` leave me with this crashlog :

```log
Supabase CLI 2.26.9
2025/06/21 18:37:20 PG Send: {"Type":"StartupMessage","ProtocolVersion":196608,"Parameters":{"database":"postgres","user":"postgres"}}
2025/06/21 18:37:20 PG Recv: {"Type":"AuthenticationSASL","AuthMechanisms":["SCRAM-SHA-256"]}
2025/06/21 18:37:20 PG Send: {"Type":"SASLInitialResponse","AuthMechanism":"SCRAM-SHA-256","Data":"n,,n=,r=rfVsozjWzvH1h5WinLqGNLRl"}
2025/06/21 18:37:20 PG Recv: {"Type":"AuthenticationSASLContinue","Data":"r=rfVsozjWzvH1h5WinLqGNLRlD2+Y/rOxWkO0dI3vtamhZBWf,s=xUvRWlzwhNgwBedJwyIxtA==,i=4096"}
2025/06/21 18:37:20 PG Send: {"Type":"SASLResponse","Data":"c=biws,r=rfVsozjWzvH1h5WinLqGNLRlD2+Y/rOxWkO0dI3vtamhZBWf,p=x2a9oAvzKr90rI8ZclFeUQR1CtGRFgzDPlGwomtgYVA="}
2025/06/21 18:37:20 PG Recv: {"Type":"AuthenticationSASLFinal","Data":"v=21XHMo2nAO1g8KvPAu9c3ba4MO73+5fWUiXVg+Wmq8k="}
2025/06/21 18:37:20 PG Recv: {"Type":"AuthenticationOK"}
2025/06/21 18:37:20 PG Recv: {"Type":"ParameterStatus","Name":"application_name","Value":""}
2025/06/21 18:37:20 PG Recv: {"Type":"ParameterStatus","Name":"client_encoding","Value":"UTF8"}
2025/06/21 18:37:20 PG Recv: {"Type":"ParameterStatus","Name":"DateStyle","Value":"ISO, MDY"}
2025/06/21 18:37:20 PG Recv: {"Type":"ParameterStatus","Name":"default_transaction_read_only","Value":"off"}
2025/06/21 18:37:20 PG Recv: {"Type":"ParameterStatus","Name":"in_hot_standby","Value":"off"}
2025/06/21 18:37:20 PG Recv: {"Type":"ParameterStatus","Name":"integer_datetimes","Value":"on"}
2025/06/21 18:37:20 PG Recv: {"Type":"ParameterStatus","Name":"IntervalStyle","Value":"postgres"}
2025/06/21 18:37:20 PG Recv: {"Type":"ParameterStatus","Name":"is_superuser","Value":"off"}
2025/06/21 18:37:20 PG Recv: {"Type":"ParameterStatus","Name":"server_encoding","Value":"UTF8"}
2025/06/21 18:37:20 PG Recv: {"Type":"ParameterStatus","Name":"server_version","Value":"15.8"}
2025/06/21 18:37:20 PG Recv: {"Type":"ParameterStatus","Name":"session_authorization","Value":"postgres"}
2025/06/21 18:37:20 PG Recv: {"Type":"ParameterStatus","Name":"standard_conforming_strings","Value":"on"}
2025/06/21 18:37:20 PG Recv: {"Type":"ParameterStatus","Name":"TimeZone","Value":"UTC"}
2025/06/21 18:37:20 PG Recv: {"Type":"BackendKeyData","ProcessID":208,"SecretKey":3014842851}
2025/06/21 18:37:20 PG Recv: {"Type":"ReadyForQuery","TxStatus":"I"}
+ ulimit -n
+ '[' '!' -z '' ']'
+ export ERL_CRASH_DUMP=/tmp/erl_crash.dump
+ ERL_CRASH_DUMP=/tmp/erl_crash.dump
+ '[' false = true ']'
+ echo 'Running migrations'
+ sudo -E -u nobody /app/bin/migrate
+ '[' true = true ']'
+ echo 'Seeding selfhosted Realtime'
+ sudo -E -u nobody /app/bin/realtime eval 'Realtime.Release.seeds(Realtime.Repo)'

==> SEE the **:eafnosupport** mention on this line below !!! ===>

** (MatchError) no match of right hand side value: {:error, {:realtime, {{:shutdown, {:failed_to_start_child, RealtimeWeb.Endpoint, {:shutdown, {:failed_to_start_child, {:ranch_listener_sup, RealtimeWeb.Endpoint.HTTP}, {:shutdown, {:failed_to_start_child, :ranch_acceptors_sup, {:listen_error, RealtimeWeb.Endpoint.HTTP, :eafnosupport}}}}}}}, {Realtime.Application, :start, [:normal, []]}}}}
    (realtime 2.56.18) lib/realtime/release.ex:23: Realtime.Release.seeds/1
    nofile:1: (file)
    (stdlib 6.1.2) erl_eval.erl:904: :erl_eval.do_apply/7
    (elixir 1.17.3) lib/code.ex:572: Code.validated_eval_string/3
2025/06/21 18:37:27 PG Send: {"Type":"Terminate"}
Stopping containers...
Pruned containers: [5061e7478eb08d784df2ee095d5c79f3a13d10ca7882774c95cfb9a52c369b89]
Pruned volumes: [supabase_config_aabcd supabase_db_abcd]
Pruned network: [supabase_network_abcd]
error running container: exit 1
```

**Comment by Mateo2335** [comment]
I have the same issue, any update?

**Comment by Lexctr** [comment]
I got the same too, the flags seems not working, some news about this ?
