### ISSUE TITLE
Runtime error on `supabase migration repair`

### ISSUE THREAD

**Issue by sidhire** [supabase/cli#1209]
**Describe the bug**
Runtime error when running the `supabase migration repair` command:

```bash
➜  web_server git:(main) npx supabase link --project-ref [my project ref]
Enter your database password (or leave blank to skip):
Finished supabase link.
➜  web_server git:(main) npx supabase migration repair 20230530034630_init --status applied
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x1031c7a80]

goroutine 1 [running]:
github.com/supabase/cli/internal/migration/repair.UpdateMigrationTable({0x103778818, 0x1400011ac80}, 0x14000154000, {0x16d803162, 0x13}, {0x16d80317f, 0x7}, {0x10377b730, 0x103fe4ee8})
	/home/runner/work/cli/cli/internal/migration/repair/repair.go:54 +0xe0
github.com/supabase/cli/internal/migration/repair.Run({0x103778818, 0x1400011ac80}, {{0x14000118c60, 0x23}, 0x198f, {0x10321e9ee, 0x8}, {0x10321e9ee, 0x8}, {0x1400051a840, ...}, ...}, ...)
	/home/runner/work/cli/cli/internal/migration/repair/repair.go:39 +0xf0
github.com/supabase/cli/cmd.glob..func43(0x103f835c0, {0x140003e5020, 0x1, 0x3?})
	/home/runner/work/cli/cli/cmd/migration.go:69 +0x130
github.com/spf13/cobra.(*Command).execute(0x103f835c0, {0x140003e4f00, 0x3, 0x3})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0x5f4
github.com/spf13/cobra.(*Command).ExecuteC(0x103f88ee0)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x35c
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/supabase/cli/cmd.Execute()
	/home/runner/work/cli/cli/cmd/root.go:95 +0x2c
main.main()
	/home/runner/work/cli/cli/main.go:8 +0x20
```

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version of CLI: 1.68.6
 - Version of Node.js: 18.5.0

**Additional context**
I also get this error upon `npx supabase migration up` though I'm not sure if it's related:
```bash
➜  web_server_new git:(main) npx supabase migration up
Error: failed to connect to `host=localhost user=postgres database=postgres`: dial error (dial tcp [::1]:54322: connect: connection refused)
Try rerunning the command with --debug to troubleshoot the error.
```

**Comment by sweatybridge** [comment]
Could you try passing in only the timestamp portion of the file? ie.

```bash
npx supabase migration repair 20230530034630 --status applied
```

We are probably missing a few checks to validate the args which results in nil pointer at run time.

**Comment by sidhire** [comment]
That worked @sweatybridge, thanks for the tip!
