### ISSUE TITLE
Incorrect storage download link host in local

### ISSUE THREAD

**Issue by bombillazo** [supabase/cli#1265]
**Describe the bug**
Local edge functions run on docker inside a container called `supabase_deno_relay` which auto-sets the SUPABASE_URL. However, it uses the internal URL of the container network. This causes issues with the JS clients that run inside edge functions with storage since it creates the download and signed URLs using the internal `http://supabase_kong_hyperion-app:8000` instead of the usual exposed `localhost:54321`api endpoint.

**To Reproduce**
1. Run edge functions with `serve` cli command
2. Generate a download link using the JS client inside an edge function
3. Try to access the download link (will be in this format: `http://supabase_kong_app:8000/storage/v1/object/public/public/users/ce5b2b2f-cfdc-4f56-a886-488dba35a184/file.txt`) instead of using `localhost:54321`

**Expected behavior**
The download link generated is accessible locally using `localhost:54321`

**Screenshots**

**Desktop (please complete the following information):**
 - Version of CLI 1.75.2
 - Version of supabase-js 2.26.0

**Comment by sweatybridge** [comment]
Yup this is a known limitation https://github.com/supabase/cli/issues/1079#issuecomment-1546058111. with a temporary workaround. I will leave this issue open for tracking.

**Comment by bombillazo** [comment]
Hey @sweatybridge , gotcha. How about if in the storage client, the download link functions check if the URL contains the internal edge function SUPABASE_URL (the kong url) used by the edge function and if it is, rewrite it to the localhost:54321 endpoint?

**Comment by sweatybridge** [comment]
Perhaps a simpler alternative is to instantiate a separate `StorageClient` in your edge function with url set to `localhost:54321`. For example,

```typescript
import { StorageClient } from '@supabase/storage-js'

const STORAGE_URL = 'http://localhost:54321/storage/v1'
const SERVICE_KEY = '<service_role_key>'

const storageClient = new StorageClient(STORAGE_URL, {
  apikey: SERVICE_KEY,
  Authorization: `Bearer ${SERVICE_KEY}`,
})
```

You can use this new client for creating signed urls and the original supabase-js client for other operations that target kong.

**Comment by bombillazo** [comment]
Hey @sweatybridge update: the suggested approach doesnt work, the URL has to be change after the fact, if not the edge function client cannot find the API endpoint:

```sh
Handler error: StorageUnknownError: error sending request for url (http://localhost:54321/object/sign/public): error trying to connect: tcp connect error: Cannot assign requested address (os error 99)
    at https://esm.sh/v127/@supabase/storage-js@2.5.1/esnext/storage-js.mjs:2:1638
    at Generator.next (<anonymous>)
    at u (https://esm.sh/v127/@supabase/storage-js@2.5.1/esnext/storage-js.mjs:2:1254)
```

I think my original approach will work and will remove the need for devs to handle this edge case any time we use the storage client in local.

**Comment by sweatybridge** [comment]
I see, thanks for investigating. Let me transfer this ticket to storage-js to see if anyone can pick it up sooner.
