### ISSUE TITLE
~/.supabase/deno binary not working on NixOS. fork/exec /home/ivand/.supabase/deno: no such file or directory

### ISSUE THREAD

**Issue by ivandimitrov8080** [supabase/cli#1311]
**Describe the bug**
Using `pnpx supabase init` or `pnpx supabase deploy...`  resulting in an error saying that the deno file isn't there, but it is.

```
❯ pnpx supabase functions deploy hello-world --project-ref uatmflnmkumsnskycpqe --debug
.../share/pnpm/store/v3/tmp/dlx-2668     |  +22 ++
.../share/pnpm/store/v3/tmp/dlx-2668     | Progress: resolved 22, reused 22, downloaded 0, added 22, done
Supabase CLI 1.77.9
fork/exec /home/ivand/.supabase/deno: no such file or directory
 ERROR  Command failed with exit code 1: supabase functions deploy hello-world --project-ref uatmflnmkumsnskycpqe --debug

pnpm: Command failed with exit code 1: supabase functions deploy hello-world --project-ref uatmflnmkumsnskycpqe --debug
    at makeError (/nix/store/9lflh3pngizwchd5ycsb6v38wn11kly9-pnpm-8.5.1/lib/node_modules/pnpm/dist/pnpm.cjs:24242:17)
    at handlePromise (/nix/store/9lflh3pngizwchd5ycsb6v38wn11kly9-pnpm-8.5.1/lib/node_modules/pnpm/dist/pnpm.cjs:24813:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.handler [as dlx] (/nix/store/9lflh3pngizwchd5ycsb6v38wn11kly9-pnpm-8.5.1/lib/node_modules/pnpm/dist/pnpm.cjs:223404:7)
    at async /nix/store/9lflh3pngizwchd5ycsb6v38wn11kly9-pnpm-8.5.1/lib/node_modules/pnpm/dist/pnpm.cjs:232806:21
    at async main (/nix/store/9lflh3pngizwchd5ycsb6v38wn11kly9-pnpm-8.5.1/lib/node_modules/pnpm/dist/pnpm.cjs:232773:34)
    at async runPnpm (/nix/store/9lflh3pngizwchd5ycsb6v38wn11kly9-pnpm-8.5.1/lib/node_modules/pnpm/dist/pnpm.cjs:233028:5)
    at async /nix/store/9lflh3pngizwchd5ycsb6v38wn11kly9-pnpm-8.5.1/lib/node_modules/pnpm/dist/pnpm.cjs:233020:7
❯ cd ~/.supabase
❯ ls -alh
total 100M
drwxr-xr-x 1 ivand users   42 Jul 13 10:00 .
drwx------ 1 ivand users  692 Jul 13 09:55 ..
-rw------- 1 ivand users   44 Jul 13 09:42 access-token
-rwxr-xr-x 1 ivand users 100M Jul 13 09:43 deno
drwxr-xr-x 1 ivand users   36 Jul 13 09:43 denos
❯ ./deno
zsh: no such file or directory: ./deno
❯ ldd deno
	linux-vdso.so.1 (0x00007fffa3fd1000)
	libdl.so.2 => /nix/store/46m4xx889wlhsdj72j38fnlyyvvvvbyb-glibc-2.37-8/lib/libdl.so.2 (0x00007fef297e0000)
	libgcc_s.so.1 => /nix/store/jd99cyc0251p0i5y69w8mqjcai8mcq7h-xgcc-12.2.0-libgcc/lib/libgcc_s.so.1 (0x00007fef251df000)
	libpthread.so.0 => /nix/store/46m4xx889wlhsdj72j38fnlyyvvvvbyb-glibc-2.37-8/lib/libpthread.so.0 (0x00007fef251da000)
	libm.so.6 => /nix/store/46m4xx889wlhsdj72j38fnlyyvvvvbyb-glibc-2.37-8/lib/libm.so.6 (0x00007fef250fa000)
	libc.so.6 => /nix/store/46m4xx889wlhsdj72j38fnlyyvvvvbyb-glibc-2.37-8/lib/libc.so.6 (0x00007fef24f14000)
	/lib64/ld-linux-x86-64.so.2 => /nix/store/46m4xx889wlhsdj72j38fnlyyvvvvbyb-glibc-2.37-8/lib64/ld-linux-x86-64.so.2 (0x00007fef297e7000)
```

**To Reproduce**
1. Use a 64 bit system without multiarch support like [NixOS](https://superuser.com/questions/912389/how-do-i-install-the-32-bit-dynamic-linker-on-64-bit-nixos)
2. Init the supabase project and create a supabase edge function
3. Enter your access token and attempt to deploy the function
4. It will fail with the error above

**Expected behavior**

I'd like to get a 64 bit deno binary out of the box and not have to worry about 32 bit support.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 ```
❯ uname -a
Linux nixos 6.1.38 #1-NixOS SMP PREEMPT_DYNAMIC Wed Jul  5 17:27:38 UTC 2023 x86_64 GNU/Linux
 ```
 - Browser (if applicable) [e.g. chrome, safari]
 - Version of CLI [e.g. v1.60.0]
 ```
❯ pnpx supabase --version
.../share/pnpm/store/v3/tmp/dlx-2774     |  +22 ++
.../share/pnpm/store/v3/tmp/dlx-2774     | Progress: resolved 22, reused 22, downloaded 0, added 22, done
1.77.9
 ```
 - Version of supabase-js (if applicable) [e.g. v2.22.0]
 - Version of Node.js (if applicable) [e.g. v16.20.0]

**Additional context**
I tried copying a 64 bit binary, but it doesn't work either. It does however fail at a different place.

```
❯ pnpx supabase functions deploy hello-world --project-ref uatmflnmkumsnskycpqe --debug
.../share/pnpm/store/v3/tmp/dlx-3174     |  +22 ++
.../share/pnpm/store/v3/tmp/dlx-3174     | Progress: resolved 22, reused 22, downloaded 0, added 22, done
Supabase CLI 1.77.9
Downloading https://github.com/denoland/deno/releases/download/v1.30.3/deno-x86_64-unknown-linux-gnu.zip
Deno is upgrading to version 1.30.3
Archive:  /tmp/.tmpT6z5Lv/deno.zip
  inflating: deno                    
error: No such file or directory (os error 2)
exit status 1
 ERROR  Command failed with exit code 1: supabase functions deploy hello-world --project-ref uatmflnmkumsnskycpqe --debug

pnpm: Command failed with exit code 1: supabase functions deploy hello-world --project-ref uatmflnmkumsnskycpqe --debug
    at makeError (/nix/store/9lflh3pngizwchd5ycsb6v38wn11kly9-pnpm-8.5.1/lib/node_modules/pnpm/dist/pnpm.cjs:24242:17)
    at handlePromise (/nix/store/9lflh3pngizwchd5ycsb6v38wn11kly9-pnpm-8.5.1/lib/node_modules/pnpm/dist/pnpm.cjs:24813:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.handler [as dlx] (/nix/store/9lflh3pngizwchd5ycsb6v38wn11kly9-pnpm-8.5.1/lib/node_modules/pnpm/dist/pnpm.cjs:223404:7)
    at async /nix/store/9lflh3pngizwchd5ycsb6v38wn11kly9-pnpm-8.5.1/lib/node_modules/pnpm/dist/pnpm.cjs:232806:21
    at async main (/nix/store/9lflh3pngizwchd5ycsb6v38wn11kly9-pnpm-8.5.1/lib/node_modules/pnpm/dist/pnpm.cjs:232773:34)
    at async runPnpm (/nix/store/9lflh3pngizwchd5ycsb6v38wn11kly9-pnpm-8.5.1/lib/node_modules/pnpm/dist/pnpm.cjs:233028:5)
    at async /nix/store/9lflh3pngizwchd5ycsb6v38wn11kly9-pnpm-8.5.1/lib/node_modules/pnpm/dist/pnpm.cjs:233020:7
❯ deno --version
deno 1.33.3 (release, x86_64-unknown-linux-gnu)
v8 11.4.183.2
typescript 5.0.4
```

**Comment by soedirgo** [comment]
> ❯ ls -alh
total 100M
drwxr-xr-x 1 ivand users   42 Jul 13 10:00 .
drwx------ 1 ivand users  692 Jul 13 09:55 ..
-rw------- 1 ivand users   44 Jul 13 09:42 access-token
-rwxr-xr-x 1 ivand users 100M Jul 13 09:43 deno
drwxr-xr-x 1 ivand users   36 Jul 13 09:43 denos
❯ ./deno
zsh: no such file or directory: ./deno

Hmm why can't zsh find the `deno` binary there?

> ❯ ldd deno

This runs the `deno` binary in your `PATH` - the Supabase CLI manages its own `deno` binary, which is in `~/.supabase/deno`.

Can you explain the issue with 32 bit that you're referring to? From what I can see all the binaries involved are 64 bit.
