### ISSUE TITLE
Can't create migration on recent CLI

### ISSUE THREAD

**Issue by Pictor13** [supabase/cli#1401]
**Describe the bug**
I can successfully create a db-diff migration with an old version of the CLI (1.68.6) but it instead fails when using a more recent version (1.86.1).

**To Reproduce**
1. install recent version via NPM
2. `supabase start`
3. `supabase db diff --schema public`

**Expected behavior**
Create migrations correctly with no error.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Version of CLI (see above)

**Additional context**
here's the output from the commands

```
supabase db diff --schema public
Connecting to local database...
Creating shadow database...
Setting up initial schema...
Applying migration 20230606024123_init.sql...
Applying migration 20230612070853_remote_commit.sql...
ERROR: relation "flow_state_created_at_idx" already exists (SQLSTATE 42P07)                            
At statement 0: CREATE INDEX flow_state_created_at_idx ON auth.flow_state USING btree (created_at DESC)
Try rerunning the command with --debug to troubleshoot the error.

$ supabase db diff --schema public --debug
Supabase CLI 1.86.1
Connecting to local database...
Creating shadow database...
2023/08/22 01:36:43 Sent Header: Host [api.moby.localhost]
2023/08/22 01:36:43 Sent Header: User-Agent [Docker-Client/unknown-version (linux)]
2023/08/22 01:36:43 Send Done
2023/08/22 01:36:43 Recv First Byte
2023/08/22 01:36:43 Sent Header: Host [api.moby.localhost]
2023/08/22 01:36:43 Sent Header: User-Agent [Docker-Client/unknown-version (linux)]
2023/08/22 01:36:43 Sent Header: Content-Length [312]
2023/08/22 01:36:43 Sent Header: Content-Type [application/json]
2023/08/22 01:36:43 Send Done
2023/08/22 01:36:43 Recv First Byte
2023/08/22 01:36:43 Sent Header: Host [api.moby.localhost]
2023/08/22 01:36:43 Sent Header: User-Agent [Docker-Client/unknown-version (linux)]
2023/08/22 01:36:43 Sent Header: Content-Length [11328]
2023/08/22 01:36:43 Sent Header: Content-Type [application/json]
2023/08/22 01:36:43 Send Done
2023/08/22 01:36:43 Recv First Byte
2023/08/22 01:36:43 Sent Header: Host [api.moby.localhost]
2023/08/22 01:36:43 Sent Header: User-Agent [Docker-Client/unknown-version (linux)]
2023/08/22 01:36:43 Sent Header: Content-Length [0]
2023/08/22 01:36:43 Sent Header: Content-Type [text/plain]
2023/08/22 01:36:43 Send Done
2023/08/22 01:36:43 Recv First Byte
2023/08/22 01:36:43 Connect Start: tcp 127.0.0.1:54320
2023/08/22 01:36:43 Connect Done: tcp 127.0.0.1:54320
2023/08/22 01:36:43 PG Send: {"Type":"StartupMessage","ProtocolVersion":196608,"Parameters":{"database":"postgres","user":"postgres"}}
panic: read tcp 127.0.0.1:32818->127.0.0.1:54320: read: connection reset by peer

goroutine 50 [running]:
github.com/supabase/cli/internal/debug.(*Proxy).DialFunc.func1()
        github.com/supabase/cli/internal/debug/postgres.go:63 +0x445
created by github.com/supabase/cli/internal/debug.(*Proxy).DialFunc
        github.com/supabase/cli/internal/debug/postgres.go:46 +0x152
```

**Comment by sweatybridge** [comment]
> ERROR: relation "flow_state_created_at_idx" already exists (SQLSTATE 42P07)                            
At statement 0: CREATE INDEX flow_state_created_at_idx ON auth.flow_state USING btree (created_at DESC)

This is a result of outdated migration file. You can either re-generate the remote_commit file or backport our recent fixes manually.

To re-generate:
1. delete local files in `supabase/migrations/*.sql`
2. drop `supabase_migrations.schema_migrations` table from hosted project
3. run `supabase db pull`

Alternatively, to apply manual fixes:
1. Edit `20230612070853_remote_commit.sql` and comment out all lines involving the `auth` schema

Hope it helps.
