### ISSUE TITLE
TypeError: Deno.memoryUsage is not a function

### ISSUE THREAD

**Issue by evelant** [supabase/cli#1528]
**Describe the bug**
I'm attempting to get the `@sentry/node` SDK working in edge runtime. I see that `Deno.memoryUsage` got added to edge-runtime 3 months ago here https://github.com/supabase/edge-runtime/blame/01926fc73271f1834e49bf99d117f657ec4671a4/crates/node/polyfills/process.ts#L233 but on cli `1.99.10` the Sentry SDK fails to report events due to `TypeError: Deno.memoryUsage is not a function`.

Has `Deno.memoryUsage` not made it into the version of edge-runtime used by the cli yet?

**To Reproduce**

```ts
import * as Sentry from "https://esm.sh/@sentry/node?target=denonext&bundle=true"


Sentry.init({
    dsn: Deno.env.get("SENTRY_DSN"),
    debug: true,
    tracesSampleRate: 1,
})

Deno.serve(async req => {
    const transaction = Sentry.startTransaction({
        op: "test",
        name:  "testing",
    })
    transaction.finish()
     return new Response(JSON.stringify({success: true}), {
            headers: { "Content-Type": "application/json" },
            status: 200,
        })
})
```

observe that sentry debug logging outputs

```

[Error] Sentry Logger [warn]: w: Event processing pipeline threw an error, original event will not be sent. Details have been sent as a new event.
 Reason: TypeError: Deno.memoryUsage is not a function
     at https://esm.sh/v132/@sentry/node@7.71.0/denonext/node.bundle.mjs:32:14635
     at Array.<anonymous> (https://esm.sh/v132/@sentry/node@7.71.0/denonext/node.bundle.mjs:26:8995)
     at https://esm.sh/v132/@sentry/node@7.71.0/denonext/node.bundle.mjs:26:9718
     at Array.forEach (<anonymous>)
     at t._executeHandlers (https://esm.sh/v132/@sentry/node@7.71.0/denonext/node.bundle.mjs:26:9623)
     at t._setResult (https://esm.sh/v132/@sentry/node@7.71.0/denonext/node.bundle.mjs:26:9481)
     at _reject (https://esm.sh/v132/@sentry/node@7.71.0/denonext/node.bundle.mjs:26:9307)
     at Array.<anonymous> (https://esm.sh/v132/@sentry/node@7.71.0/denonext/node.bundle.mjs:26:8979)
     at https://esm.sh/v132/@sentry/node@7.71.0/denonext/node.bundle.mjs:26:9718
     at Array.forEach (<anonymous>) {
   name: "w",
   logLevel: "warn"
```

**Expected behavior**
Deno node apis should all work correctly

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: macos 13.5.2
 - Browser (if applicable) N/A
 - Version of CLI 1.99.10
 - Version of supabase-js (if applicable) N/A
 - Version of Node.js (if applicable) N/A

**Additional context**
N/A

**Comment by sweatybridge** [comment]
Transferring to edge runtime repo because it likely requires changes to the container.
