### ISSUE TITLE
Serve command does not resolve local shared modules (InvalidWorkerCreation)

### ISSUE THREAD

**Issue by mijorus** [supabase/cli#1559]
Hi,
I want to use some shared modules  with my supabase edge function. 
This is my folder structure:

- MacOS Sonoma
- » npx supabase -v »  1.100.1

```
supabase/
├── config.toml
├── functions
│   ├── _shared
│   │   ├── ErrorResponse.ts
│   │   ├── JsonResponse.ts
│   │   └── headers.ts
│   ├── test_function
│   │   └── index.ts
```

The import_map is:

```
{
    "imports": {
        "@supabase/supabase-js": "https://esm.sh/@supabase/supabase-js@2.7.1",
        "@shared/": "./_shared/"
    }
}
```

Imports happen with:

```
import { headers } from '@shared/headers.ts';
```

Result:
```sh
An error has occured
Failed to load module: "file:///home/deno/_shared/headers.ts" - No such file or directory (os error 2)
InvalidWorkerCreation: worker boot error
    at async Function.create (ext:sb_user_workers/user_workers.js:124:15)
    at async Server.<anonymous> (file:///home/deno/main/index.ts:110:20)
    at async Server.#respond (https://deno.land/std@0.182.0/http/server.ts:220:18) {
  name: "InvalidWorkerCreation"
}
```

Expected result:
it should resolve local shared modules

**Comment by mijorus** [comment]
Sorry for this bug, I'm reporting what happened to me.

First, this does not work:
```
{
    "imports": {
        "@supabase/supabase-js": "https://esm.sh/@supabase/supabase-js@2.7.1",
        "@shared/": "./_shared/"
    }
}
```

So, just don't do it.

My issue was related to the fact that I has importing a file without the `.ts` extension, it took me a while before I realised it.
Then, I tried different solutions trying to fix this bug, but I just couldn't see it
