### ISSUE TITLE
Problem with Deno and edge functions after project update

### ISSUE THREAD

**Issue by zechkonja** [supabase/cli#1629]
**Describe the bug**
After we updated supabase project and deployed our edge function we have got this error

event loop error: TypeError: Deno.stat is not a function
    at Connection.#openSocketConnection (https://deno.land/x/postgres@v0.17.0/connection/connection.ts:172:35)
    at Connection.#startup (https://deno.land/x/postgres@v0.17.0/connection/connection.ts:222:45)
    at Connection.startup (https://deno.land/x/postgres@v0.17.0/connection/connection.ts:360:40)
    at PoolClient.connect (https://deno.land/x/postgres@v0.17.0/client.ts:161:36)
    at https://deno.land/x/postgres@v0.17.0/pool.ts:165:30
    at Function.from (<anonymous>)
    at Pool.#initialize (https://deno.land/x/postgres@v0.17.0/pool.ts:160:31)
    at new Pool (https://deno.land/x/postgres@v0.17.0/pool.ts:87:39)
    at file:///Users/nemanjanikolic/WebstormProjects/onewheel-blog/supabase/functions/get-todays-records/index.ts:4:14

this is code that we are using

```
import { Pool } from "postgres";
import { serve } from "server";

const pool = new Pool(
  {
    tls: { enabled: false },
    database: "postgres",
    hostname: Deno.env.get('DB_HOST'),
    user: "postgres",
    port: 5432,
    password: Deno.env.get('DB_PASSWORD'),
  },
  1
);
```

and these are import maps:

```
{
    "imports": {
      "server": "https://deno.land/std@0.199.0/http/server.ts",
      "postgres": "https://deno.land/x/postgres@v0.17.0/mod.ts"
    }
  }
```

Please help :D

**Comment by zechkonja** [comment]
![image-Oct-30-2023-09-06-23-7550-PM](https://github.com/supabase/cli/assets/34709150/ae19c6b7-f324-4a23-8329-916a24627990)
