### ISSUE TITLE
npx supabase start requires internet connection.

### ISSUE THREAD

**Issue by chrisb2244** [supabase/cli#1635]
**Describe the bug**
Running the start command checks if the images are up to date by polling https://public.ecr.aws/v2.

This requires a network connection - failing gives an i/o timeout error and retries a couple of times, then fails and suggests running with --debug.

**To Reproduce**
1. Get a working supabase cli setup (e.g. supabase start works)
2. supabase stop
3. Disconnect network connection
4. supabase start

**Expected behavior**
Should be able to run a tool specifically discussing local/offline development without an initial connection.
I'd be fine with a cli flag to disable checking for updates or similar (or even just continuing on fail, if required, but that will obviously require the timeout to occur first, not the best DX).

**Desktop (please complete the following information):**
 - OS: WSL2 on Windows
 - Version of CLI 1.110.1
 - Version of Node.js 18.18.2

**Comment by chrisb2244** [comment]
Seems like the code that triggers a fetch is here: https://github.com/supabase/cli/blob/main/internal/utils/docker.go#L241 which indicates it only tries to pull if "not cached".

Testing with/without network shows that even with network connection, I still had an error:
```
$ npx supabase start 
Error response from daemon: manifest for public.ecr.aws/supabase/postgres:14.1.0.19 not found: manifest unknown: Requested image not found
Retrying after 4s: public.ecr.aws/supabase/postgres:14.1.0.19
```

Here, the version requested is 14.1.0.19 (as found in the `.temp/postgres-version` file, and on inspection, the online app.supabase.io page for my project (so the file, as written by [the link operation](https://github.com/supabase/cli/blob/main/internal/link/link.go#L217), had the 'correct' version).
Checking `docker image ls` shows the image that was used when I first started the setup was probably 
```
$ docker image ls
...
public.ecr.aws/supabase/postgres        14.1.0.89          667ab5e628e0   12 months ago   4.21GB
```

So this problem looks like it might be driven by writing the (correct) database version to the temp file, then not being able to actually get that image anymore.
Changing the `.temp/postgres-version` file to read `14.1.0.89` allows the images to (attempt to) start without network connection, although I'm unsure if that would cause other peculiarities later.
```
npx supabase start 
Applying migration 20231105031024_remote_schema.sql...
Seeding data supabase/seed.sql...

... error later...
```

I'm not sure what the appropriate resolution of this issue would be, if the above is actually the mechanism causing the failure. Updating the postgres-version file (and, presumably, if required other -version files) to an available/downloaded image works, but probably isn't really in keeping with the expected behaviour (that `link` should produce files which match the remote db?)

Warning that the image is unavailable, and you should update the (remote) database before successfully linking would maybe be an option if that were easier with supabase, but I only see the option to upgrade to "The latest version of Postgres (15.1.0.131)" in the dashboard (which might be an option for me, but probably can't be relied upon as a general solution). It also wouldn't be a great experience when trying to set up local development to have the patch version prevent you being able to link your remote db.

Perhaps the version files can be adjusted (or duplicated with another name) to store the remote db values (as currently) and then a less specific tag that can be used for images (e.g. probably `14.1.0` would work and reduce the chance of mismatch and a required pull? But I don't know of a way to do this with Docker tags, so I think it would depend on the upstream image repository storing a less specific tag and updating what it points to if required)?

**Comment by sweatybridge** [comment]
Could you check the `major_version` field of your `supabase/config.toml`? CLI only tries to match remote version for major version 15. https://github.com/supabase/cli/blob/24cf1b8f76737b23502e883bd5f2ea3c8f194126/internal/utils/config.go#L428

This is because we don't have all versions of docker image published for PG14 so we cannot guarantee compatibility for versions other than 14.1.0.89.

If you get a chance though, I recommend upgrading to PG15. You would benefit from reduced memory usage and smaller image size when developing locally.

**Comment by chrisb2244** [comment]
As you suspected, there was a mismatch in the `config.toml` file (it was 15). 

I don't remember seeing any warning/error relating to that from `supabase link`, which I believe generated the file for me (but I may have mangled it at some point whilst comparing with an older generated file from ~1yr previously), but perhaps I overlooked it. Unfortunately, that makes for a useless issue report...

It's good to know that this shouldn't be the case - if you'd like me to try and investigate where it went wrong in my setup, I can run through again after deleting the supabase directory and configurations and regenerating new config files, but if you prefer to simply close the issue as 'problem exists between chair and keyboard' (or as, this only occurs in old versions, solution is upgrade), then that's also fine for me.

**Comment by sweatybridge** [comment]
We have addressed this problem in the beta release by respecting the major version set in config.toml. Hope it's less confusing now. https://github.com/supabase/cli/pull/1842

**Comment by eqoram** [comment]
I am also getting errors when I am trying to run supabase start without an internet connection.
First time when I tried to run it I got this error:
`WARNING: analytics requires mounting default docker socket: /var/run/docker.sock
failed to pull docker image: Error response from daemon: failed to resolve reference "public.ecr.aws/supabase/edge-runtime:v1.66.1": failed to do request: Head "https://public.ecr.aws/v2/supabase/edge-runtime/manifests/v1.66.1": dialing public.ecr.aws:443 container via direct connection because  has no HTTPS proxy: connecting to public.ecr.aws:443: dial tcp: lookup public.ecr.aws: no such host
Retrying after 4s: public.ecr.aws/supabase/edge-runtime:v1.66.1
failed to pull docker image: Error response from daemon: failed to resolve reference "public.ecr.aws/supabase/edge-runtime:v1.66.1": failed to do request: Head "https://public.ecr.aws/v2/supabase/edge-runtime/manifests/v1.66.1": dialing public.ecr.aws:443 container via direct connection because  has no HTTPS proxy: connecting to public.ecr.aws:443: dial tcp: lookup public.ecr.aws: no such host
Retrying after 8s: public.ecr.aws/supabase/edge-runtime:v1.66.1
Stopping containers...
failed to pull docker image: Error response from daemon: failed to resolve reference "public.ecr.aws/supabase/edge-runtime:v1.66.1": failed to do request: Head "https://public.ecr.aws/v2/supabase/edge-runtime/manifests/v1.66.1": dialing public.ecr.aws:443 container via direct connection because  has no HTTPS proxy: connecting to public.ecr.aws:443: dial tcp: lookup public.ecr.aws: no such host
Try rerunning the command with --debug to troubleshoot the error.`

Second time I got this one:
`Using workdir /Users/eqoram/Documents/coding/quasar/disruptive
WARNING: analytics requires mounting default docker socket: /var/run/docker.sock
supabase_edge_runtime_disruptive container logs:
Download https://deno.land/std/http/status.ts
Download https://deno.land/std/path/posix/mod.ts
Download https://deno.land/x/jose@v4.13.1/index.ts
worker boot error: failed to create the graph: Import 'https://deno.land/std/http/status.ts' failed: error sending request for url (https://deno.land/std/http/status.ts)
    at file:///root/index.ts:1:42
Error: main worker boot error

Caused by:
    0: worker boot error
    1: failed to create the graph
    2: Import 'https://deno.land/std/http/status.ts' failed: error sending request for url (https://deno.land/std/http/status.ts)
           at file:///root/index.ts:1:42
Stopping containers...
Error status 503: 
Try rerunning the command with --debug to troubleshoot the error.`

**Comment by sweatybridge** [comment]
@eqoram have you ran `npx supbase start` once successfully with internet?

Offline mode only works if all the dependencies are already cached locally.

**Comment by eqoram** [comment]
@sweatybridge Thanks for the quick response! Yes I did. I installed it with Homebrew though so it's just `supabase start` for me but I guess it should not matter

**Comment by sweatybridge** [comment]
I see, then the 2nd error came from edge runtime downloading new dependencies. The dependencies should be cached in docker volume after initial load. So may I asks if you made changes to functions that perhaps required new dependencies?

**Comment by eqoram** [comment]
Nope. I don't even use edge functions in my project. I basically started supabase with an internet connection and then cut the connection and tried again.
