### ISSUE TITLE
Unable to build function that imports modules with node specifiers

### ISSUE THREAD

**Issue by zyc9012** [supabase/cli#1640]
**Describe the bug**
When the function imports with [node specifiers](https://docs.deno.com/runtime/manual/node/node_specifiers), e.g. `node:https`, it throws error.

```
error: Uncaught (in promise) Error: Module not found "node:https".
      const ret = new Error(getStringFromWasm0(arg0, arg1));
                  ^
    at __wbg_new_8d2af00bc1e329ee (https://deno.land/x/eszip@v0.35.0/eszip_wasm.generated.js:513:19)
    at <anonymous> (https://deno.land/x/eszip@v0.35.0/eszip_wasm_bg.wasm:1:1559899)
    at <anonymous> (https://deno.land/x/eszip@v0.35.0/eszip_wasm_bg.wasm:1:1398157)
    at <anonymous> (https://deno.land/x/eszip@v0.35.0/eszip_wasm_bg.wasm:1:1895031)
    at __wbg_adapter_40 (https://deno.land/x/eszip@v0.35.0/eszip_wasm.generated.js:229:6)
    at real (https://deno.land/x/eszip@v0.35.0/eszip_wasm.generated.js:213:14)
```

**To Reproduce**
Create a function like this and deploy
```
import https from "node:https";

Deno.serve(async (req) => {
  // do something with `https`
  return new Response("abc")
})
```

**Expected behavior**
It can build the function succesfully.

**Additional context**
Related issue https://github.com/serpapi/serpapi-javascript/issues/20

**Comment by kamilogorek** [comment]
npm specifiers are not supported just yet, please refer to https://github.com/supabase/edge-runtime/issues/78 for future updates. Thanks!
