### ISSUE TITLE
Local Edge functions: event loop error after a few minutes

### ISSUE THREAD

**Issue by ChuckJonas** [supabase/cli#1648]
**Describe the bug**

It seems that after my edge function has been running locally for some time (perhaps a few minutes) I start to get these messages in the logs:

```
wall clock duration warning. isolate: df3c6dc8-dcc9-4348-a278-e0e1ff102fc3
wall clock duration warning. isolate: 93b745a9-cdb0-49a0-ae88-514a87391cd6
wall clock duration warning. isolate: ce00ba14-d7f7-4e27-8b6e-92191f485a81
wall clock duration warning. isolate: 39ebddfd-8b3e-4af6-a966-178f821877b6
```

And then eventually I see this:
```
event loop error: TypeError: Cannot convert undefined or null to object
    at slice (<anonymous>)
    at new DOMException (ext:deno_web/01_dom_exception.js:126:14)
    at [[[signalAbort]]] (ext:deno_web/03_abort_signal.js:83:14)
    at AbortController.abort (ext:deno_web/03_abort_signal.js:172:30)
    at file:///home/deno/main/index.ts:147:31
    at Object.action (ext:deno_web/02_timers.js:151:11)
    at handleTimerMacrotask (ext:deno_web/02_timers.js:65:10)
    at eventLoopTick (ext:core/01_core.js:189:21)
```

After that error happens, all my requests fail with this:
```
Error in worker connection: connection closed before message completed
request failed (uri: "/my-function" reason: hyper::Error(Canceled, "connection was not ready"))
```

The function is as simple as this:
```ts
Deno.serve(async (req) => {
  return new Response(
    JSON.stringify({ publicToken: "123" }),
    {
      headers: { "Content-Type": "application/json" },
    }
  );
});
```

**To Reproduce**
1. Create a new function with the above code
2. run `supabase functions serve` 
3. Call the function at least once (not sure if this is actually necessary)
4. Wait a few minutes... the above error should be `event loop error` should eventually occur
5. Try to call the function again.  You will get `"connection was not ready"` error 

**Expected behavior**
Local functions should not randomly crash after only a few minute :)

**Desktop (please complete the following information):**
 - OS: OSX
 - Version of CLI: `1.110.1`

**Additional context**

At least one other person has reported experiencing this problem in the [supabase discord](https://discord.com/channels/839993398554656828/1171844295154737268/1171844295154737268).

**Comment by ChuckJonas** [comment]
I rolled back to `1.106.1` and the issue seem to go away.
