### ISSUE TITLE
Function download throws RuntimeError: unreachable error

### ISSUE THREAD

**Issue by phamhieu** [supabase/cli#1712]
**Describe the bug**

When i use functions download command, it throws RuntimeError: unreachable error

**To Reproduce**
1. Go to command line
2. Type `supabase functions download hello --debug`
3. See error

**Expected behavior**
The function should be downloaded to view on my pc

**Screenshots**

```
Error downloading function: exit status 1                                     
error: Uncaught (in promise) RuntimeError: unreachable                        
    at <anonymous> (wasm://wasm/005e7f22:1:876644)                            
    at <anonymous> (wasm://wasm/005e7f22:1:882115)                            
    at <anonymous> (wasm://wasm/005e7f22:1:881672)                            
    at <anonymous> (wasm://wasm/005e7f22:1:876405)                            
    at <anonymous> (wasm://wasm/005e7f22:1:605349)                            
    at decompress (https://deno.land/x/brotli@0.1.7/wasm.js:3:1293844)        
    at decompress (https://deno.land/x/brotli@0.1.7/mod.ts:51:10)             
    at extractSource (file:///Users/xxxxxx/.supabase/denos/extract.ts:44:24)
```

**Desktop (please complete the following information):**
 - OS: macos
 - Browser (if applicable): chome
 - Version of CLI: 1.115.4

**Additional context**

**Comment by topperspal** [comment]
I am also facing the same error on windows 11.

```
error: Uncaught (in promise) RuntimeError: unreachable
    at <anonymous> (wasm://wasm/005e7f22:1:876644)
    at <anonymous> (wasm://wasm/005e7f22:1:882115)
    at <anonymous> (wasm://wasm/005e7f22:1:881672)
    at <anonymous> (wasm://wasm/005e7f22:1:876405)
    at <anonymous> (wasm://wasm/005e7f22:1:605349)
    at decompress (https://deno.land/x/brotli@0.1.7/wasm.js:3:1293844)
    at decompress (https://deno.land/x/brotli@0.1.7/mod.ts:51:10)
    at extractSource (file:///C:/Users/vikas/.supabase/denos/extract.ts:44:24)
```

**Comment by topperspal** [comment]
I am also facing the same error on windows 11.

```
error: Uncaught (in promise) RuntimeError: unreachable
    at <anonymous> (wasm://wasm/005e7f22:1:876644)
    at <anonymous> (wasm://wasm/005e7f22:1:882115)
    at <anonymous> (wasm://wasm/005e7f22:1:881672)
    at <anonymous> (wasm://wasm/005e7f22:1:876405)
    at <anonymous> (wasm://wasm/005e7f22:1:605349)
    at decompress (https://deno.land/x/brotli@0.1.7/wasm.js:3:1293844)
    at decompress (https://deno.land/x/brotli@0.1.7/mod.ts:51:10)
    at extractSource (file:///C:/Users/username/.supabase/denos/extract.ts:44:24)
```

**Comment by sweatybridge** [comment]
Should be fixed in latest beta release `npx supabase@beta functions download hello`
