### ISSUE TITLE
ApiError: Database error finding user from email link

### ISSUE THREAD

**Issue by zhihengGet** [supabase/cli#1860]
**Describe the bug**

im using sveltekit with supabase cli , after clicking on the confimation link  i got following error ,the code i used is from supabase examples https://supabase.com/docs/guides/auth/server-side/email-based-auth-with-pkce-flow-for-ssr?framework=sveltekit

error in confirm otp AuthApiError: Database error finding user from email link 
node_modules\@supabase\gotrue-js\dist\main\lib\fetch.js:43:11)

windows with podman
version 1.133.3

**Comment by robpetty** [comment]
@zhihengGet how did you work around this?

Locally I got this to work fine.

Now I am trying in production, but I am getting this error as well:

```
eL [AuthApiError]: Database error finding user from email link
    at eX (/var/task/.next/server/chunks/967.js:1:110420)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async e1 (/var/task/.next/server/chunks/967.js:1:111362)
    at async eQ (/var/task/.next/server/chunks/967.js:1:111036)
    at async ao.verifyOtp (/var/task/.next/server/chunks/967.js:1:127881)
    at async p (/var/task/.next/server/app/auth/confirm/route.js:1:1853)
    at async /var/task/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:41960 {
  __isAuthError: true,
  status: 500
}
```
