### ISSUE TITLE
Error on 'npx supabase start' When Linking New Local Project to Existing Remote Supabase Project

### ISSUE THREAD

**Issue by martijnvanderpol** [supabase/cli#1877]
**Describe the bug**
When running `npx supabase start` in a new local project and attempting to link to an existing Supabase project, the process fails with the error: "Migration failed. Reason: An error occurred running 'storage-schema'". This is particularly interesting because I don't have any migrations in my project.

**To Reproduce**

1. Initialize a fresh Supabase folder by running `npx supabase init`.
2. Log in to your Supabase account by running `npx supabase login`.
3. Link your remote Supabase project by executing `npx supabase link --project-ref PROJECT_REF`.
4. Enter your database password.
5. Run `npx supabase start`.
6. Observe the error as shown in the screenshot.

**Expected behavior**
I expect that all containers would successfully run, allowing me access to the local Supabase Studio.

**Screenshots**
[Screenshot of error](https://snipboard.io/5xTQu4.jpg)
[Project Structure](https://snipboard.io/7vUy0x.jpg)

**Desktop:**
 - OS: MacOS 14.0 (23A344)
 - Docker Client: OrbStack
 - Version of CLI: 1.136.2
 - Version of Node.js: v18.17.0

**Additional context**
I've successfully run `npx supabase start` in another project I am working on, which makes it surprising that this issue occurs in a fresh project that I am trying to link to an existing remote Supabase project.

**Comment by andrea-giachetto** [comment]
Same exact behaviour here, I've tried to use the beta version (1.137.0) but it's not working as well.

**Comment by sweatybridge** [comment]
Could you also run `npx supabase services` and share the output here?

Perhaps there is an incompatibility with the storage version after linking.

**Comment by martijnvanderpol** [comment]
Thanks for your quick response, @sweatybridge! Sure thing. This is the output of my `npx supabase services`:

`
| SERVICE IMAGE           | LOCAL                | LINKED     |
|-------------------------|----------------------|------------|
| supabase/postgres       | 15.1.0.49            | 15.1.0.49  |
| supabase/gotrue         | v2.132.3             | v2.132.3   |
| postgrest/postgrest     | v10.2.0              | v10.2.0    |
| supabase/realtime       | v2.25.50             | -          |
| supabase/storage-api    | v0.46.3              | v0.46.3    |
| supabase/edge-runtime   | v1.32.0              | -          |
| supabase/studio         | 20240101-8e4a094     | -          |
| supabase/postgres-meta  | v0.75.0              | -          |
| supabase/logflare       | 1.4.0                | -          |
| bitnami/pgbouncer       | 1.20.1-debian-11-r39 | -          |
| darthsim/imgproxy       | v3.8.0               | -          |
`

**Comment by andrea-giachetto** [comment]
My `npx supabase services` output:
  
    supabase/postgres      │ 15.1.1.2             │ 15.1.1.2
    supabase/gotrue        │ v2.132.3             │ v2.132.3
    postgrest/postgrest    │ v12.0.2              │ v12.0.2
    supabase/realtime      │ v2.25.50             │ -
    supabase/storage-api   │ v0.46.3              │ v0.46.3
    supabase/edge-runtime  │ v1.32.0              │ -
    supabase/studio        │ 20240101-8e4a094     │ -
    supabase/postgres-meta │ v0.75.0              │ -
    supabase/logflare      │ 1.4.0                │ -
    bitnami/pgbouncer      │ 1.20.1-debian-11-r39 │ -
    darthsim/imgproxy      │ v3.8.0               │ -

**Comment by andrea-giachetto** [comment]
I add I can't run even `supabase start` on locally (macos 14.1 (23B2073)) with the CLI being at **v1.136.2**.
It get stuck at the **Starting database from backup** step and it quits after some minutes printing _database is not healthy_.
In my Docker Desktop app I read:

> 2024-01-24 20:40:14 PostgreSQL Database directory appears to contain a database; Skipping initialization
> 2024-01-24 20:40:14 
> 2024-01-24 20:39:23 2024-01-24 19:39:23.300 GMT [10] LOG:  could not open configuration file "/etc/postgresql-custom/read-replica.conf": No such file or directory
> 2024-01-24 20:39:23 2024-01-24 19:39:23.300 GMT [10] FATAL:  configuration file "/etc/postgresql/postgresql.conf" contains errors
> 2024-01-24 20:40:14 2024-01-24 19:40:14.650 GMT [10] LOG:  could not open configuration file "/etc/postgresql-custom/read-replica.conf": No such file or directory
> 2024-01-24 20:40:14 2024-01-24 19:40:14.650 GMT [10] FATAL:  configuration file "/etc/postgresql/postgresql.conf" contains errors

The only thing I did is to upgrade supabase CLI though the brew CLI.
I've noticed that because on my Github action I kept having the error message @martijnvanderpol reported on the screenshot and I couldn't deploy my changes.

**Comment by matthewmorek** [comment]
I have the same issue, with or without migrations present, even on a clean project with no prior configuration. Supabase CLI v1.137.0 (beta) is also affected.

```
/app/dist/database/migrate.js:104
            const error = new Error(`Migration failed. Reason: ${e.message}`);
                          ^

Error: Migration failed. Reason: An error occurred running 'storage-schema'. Rolled back this migration. No further migrations were run. Reason: role "anon" already exists
    at /app/dist/database/migrate.js:104:27
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /app/dist/database/migrate.js:149:28
    ... 2 lines matching cause stack trace ...
    at async /app/dist/server.js:23:9 {
  cause: Error: An error occurred running 'storage-schema'. Rolled back this migration. No further migrations were run. Reason: role "anon" already exists
      at /app/node_modules/postgres-migrations/dist/run-migration.js:36:15
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async /app/dist/database/migrate.js:98:32
      at async /app/dist/database/migrate.js:149:28
      at async connectAndMigrate (/app/dist/database/migrate.js:48:9)
      at async runMigrationsOnTenant (/app/dist/database/migrate.js:35:5)
      at async /app/dist/server.js:23:9
}

Node.js v18.19.0
```

**Comment by adamwattis** [comment]
Experiencing the same issue:
```
/app/dist/database/migrate.js:104
            const error = new Error(`Migration failed. Reason: ${e.message}`);
                          ^

Error: Migration failed. Reason: An error occurred running 'storage-schema'. Rolled back this migration. No further migrations were run. Reason: role "anon" already exists
    at /app/dist/database/migrate.js:104:27
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /app/dist/database/migrate.js:149:28
    ... 2 lines matching cause stack trace ...
    at async /app/dist/scripts/migrate-call.js:10:5 {
  cause: Error: An error occurred running 'storage-schema'. Rolled back this migration. No further migrations were run. Reason: role "anon" already exists
      at /app/node_modules/postgres-migrations/dist/run-migration.js:36:15
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async /app/dist/database/migrate.js:98:32
      at async /app/dist/database/migrate.js:149:28
      at async connectAndMigrate (/app/dist/database/migrate.js:48:9)
      at async runMigrationsOnTenant (/app/dist/database/migrate.js:35:5)
      at async /app/dist/scripts/migrate-call.js:10:5
}

Node.js v18.19.0
error running container: exit 1

```

**Comment by mkazimahmed** [comment]
Experiencing the same issue

/app/dist/database/migrate.js:104
            const error = new Error(`Migration failed. Reason: ${e.message}`);
                          ^

Error: Migration failed. Reason: An error occurred running 'storage-schema'. Rolled back this migration. No further migrations were run. Reason: role "anon" already exists
    at /app/dist/database/migrate.js:104:27
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /app/dist/database/migrate.js:149:28
    ... 2 lines matching cause stack trace ...
    at async /app/dist/server.js:23:9 {
  cause: Error: An error occurred running 'storage-schema'. Rolled back this migration. No further migrations were run. Reason: role "anon" already exists
      at /app/node_modules/postgres-migrations/dist/run-migration.js:36:15
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async /app/dist/database/migrate.js:98:32
      at async /app/dist/database/migrate.js:149:28
      at async connectAndMigrate (/app/dist/database/migrate.js:48:9)
      at async runMigrationsOnTenant (/app/dist/database/migrate.js:35:5)
      at async /app/dist/server.js:23:9
}

Node.js v18.19.0
service not healthy: [supabase_storage_Projects]

**Comment by brnhynh** [comment]
We're having this issue after updating Supabase CLI (version 1.136.2) and running `supabase start`. Here are the outputs:

```
supabase start
1.4.0: Pulling from supabase/logflare
261da4162673: Pull complete 
7d2a960092ca: Pull complete 
cab6fd4eb5d1: Pull complete 
05267fd6f742: Pull complete 
1e3eeb829493: Pull complete 
4cc5b43cfbf9: Pull complete 
455249722616: Pull complete 
4f4fb700ef54: Pull complete 
105209f6e8d8: Pull complete 
Digest: sha256:e693c787ffe1ae17b6e4e920a3cdd212416d3e1f97e1bd7cb5b67de0abbb0264
Status: Downloaded newer image for public.ecr.aws/supabase/logflare:1.4.0
2.8.1: Pulling from supabase/kong
9b18e9b68314: Pull complete 
7fd91e922960: Pull complete 
450997ae687c: Pull complete 
d8380bfcbd9b: Pull complete 
Digest: sha256:1b53405d8680a09d6f44494b7990bf7da2ea43f84a258c59717d4539abf09f6d
Status: Downloaded newer image for public.ecr.aws/supabase/kong:2.8.1
v2.132.3: Pulling from supabase/gotrue
b8180c93b172: Pull complete 
896f7a45b28c: Pull complete 
f601026daa99: Pull complete 
3fd170a1e9e8: Pull complete 
6e3acd8bfe40: Pull complete 
61462962e623: Pull complete 
Digest: sha256:1bfae25acead513fbd459679a08463a1fc679769e6586c773cfc32d26c5b6dcf
Status: Downloaded newer image for public.ecr.aws/supabase/gotrue:v2.132.3
3.0.3: Pulling from supabase/inbucket
f97344484467: Pull complete 
c93cd632d565: Pull complete 
7cadd1efbbe6: Pull complete 
9853c0941218: Pull complete 
b6f6817b1d4a: Pull complete 
c5c956c4e9fc: Pull complete 
59cbfb43403a: Pull complete 
9c842edb6049: Pull complete 
Digest: sha256:dc912ab76de647ca2a363fe285515e512e964cf699166773f3c2c73f5e7f71c0
Status: Downloaded newer image for public.ecr.aws/supabase/inbucket:3.0.3
v2.25.50: Pulling from supabase/realtime
66dbba0fb1b5: Pull complete 
4166bd72e87a: Pull complete 
5dd8dfaab4d9: Pull complete 
07484305c37f: Pull complete 
a29e87bf71ee: Pull complete 
933c3bd59c23: Pull complete 
9614f9b82227: Pull complete 
3031aaa00e8d: Pull complete 
2faab5f119c5: Pull complete 
f54398b16e61: Pull complete 
2ffe6f08fe84: Pull complete 
0aa8ae17bf21: Pull complete 
Digest: sha256:c54ae830834a0a31587c22045a6e6c6743b5f9335527a179681bef34ca03260b
Status: Downloaded newer image for public.ecr.aws/supabase/realtime:v2.25.50
v12.0.2: Pulling from supabase/postgrest
d519a3a2a796: Already exists 
4e0059d9a247: Pull complete 
1ed0fb2de4f4: Pull complete 
Digest: sha256:79369c0cdf9d7112ed4e327bc1b80156be11575dd66fbda245077a2d13b803bc
Status: Downloaded newer image for public.ecr.aws/supabase/postgrest:v12.0.2
v3.8.0: Pulling from supabase/imgproxy
df8e44b0463f: Pull complete 
b0f1dd53d7c3: Pull complete 
ead8ac122bf1: Pull complete 
4667765ff03a: Pull complete 
744485a3a3a9: Pull complete 
8650da0c91b5: Pull complete 
Digest: sha256:0facd355d50f3be665ebe674486f2b2e9cdaebd3f74404acd9b7fece2f661435
Status: Downloaded newer image for public.ecr.aws/supabase/imgproxy:v3.8.0
v1.32.0: Pulling from supabase/edge-runtime
a5573528b1f0: Pull complete 
634d09a65844: Pull complete 
4f5c02c75ddc: Pull complete 
8b21a364ecf7: Pull complete 
Digest: sha256:fa4e2d1e0477913f372fcaf7f01dbfbcde470f07b9957057756b0e1327509b20
Status: Downloaded newer image for public.ecr.aws/supabase/edge-runtime:v1.32.0
v0.75.0: Pulling from supabase/postgres-meta
2c6d21737d83: Pull complete 
2398be8db5f7: Pull complete 
a8aaaf4c9c12: Pull complete 
b2640ab71335: Pull complete 
8f5ae29d9d42: Pull complete 
0f1f70e3581e: Pull complete 
1b05712d5904: Pull complete 
a7e8636ebe6f: Pull complete 
de9796f4c8ce: Pull complete 
Digest: sha256:c5042d12dbf0366a6e27dafb2bb1f2c0d61662da7fb8e065ab51b6c15a964145
Status: Downloaded newer image for public.ecr.aws/supabase/postgres-meta:v0.75.0
20240101-8e4a094: Pulling from supabase/studio
24e221e92a36: Pull complete 
dbc596c5cca5: Pull complete 
b665ed4ee4f7: Pull complete 
392ddf2ad556: Pull complete 
cb3d1a19897b: Pull complete 
bcec8420c1a9: Pull complete 
684c2e9fdfb4: Pull complete 
eec526392e29: Pull complete 
7847b6d22acf: Pull complete 
b5ae73a7697d: Pull complete 
Digest: sha256:305ffb3c0e8aa72bcdca451895b88a7ed11f613ebbaf22cd5086e6a94ef73b01
Status: Downloaded newer image for public.ecr.aws/supabase/studio:20240101-8e4a094
supabase_storage_xyz container logs:
/app/dist/database/migrate.js:104
            const error = new Error(`Migration failed. Reason: ${e.message}`);
                          ^

Error: Migration failed. Reason: An error occurred running 'storage-schema'. Rolled back this migration. No further migrations were run. Reason: role "anon" already exists
    at /app/dist/database/migrate.js:104:27
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /app/dist/database/migrate.js:149:28
    ... 2 lines matching cause stack trace ...
    at async /app/dist/server.js:23:9 {
  cause: Error: An error occurred running 'storage-schema'. Rolled back this migration. No further migrations were run. Reason: role "anon" already exists
      at /app/node_modules/postgres-migrations/dist/run-migration.js:36:15
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async /app/dist/database/migrate.js:98:32
      at async /app/dist/database/migrate.js:149:28
      at async connectAndMigrate (/app/dist/database/migrate.js:48:9)
      at async runMigrationsOnTenant (/app/dist/database/migrate.js:35:5)
      at async /app/dist/server.js:23:9
}

Node.js v18.19.0
/app/dist/database/migrate.js:104
            const error = new Error(`Migration failed. Reason: ${e.message}`);
                          ^

Error: Migration failed. Reason: An error occurred running 'storage-schema'. Rolled back this migration. No further migrations were run. Reason: role "anon" already exists
    at /app/dist/database/migrate.js:104:27
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /app/dist/database/migrate.js:149:28
    ... 2 lines matching cause stack trace ...
    at async /app/dist/server.js:23:9 {
  cause: Error: An error occurred running 'storage-schema'. Rolled back this migration. No further migrations were run. Reason: role "anon" already exists
      at /app/node_modules/postgres-migrations/dist/run-migration.js:36:15
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async /app/dist/database/migrate.js:98:32
      at async /app/dist/database/migrate.js:149:28
      at async connectAndMigrate (/app/dist/database/migrate.js:48:9)
      at async runMigrationsOnTenant (/app/dist/database/migrate.js:35:5)
      at async /app/dist/server.js:23:9
}

Node.js v18.19.0
/app/dist/database/migrate.js:104
            const error = new Error(`Migration failed. Reason: ${e.message}`);
                          ^

Error: Migration failed. Reason: An error occurred running 'storage-schema'. Rolled back this migration. No further migrations were run. Reason: role "anon" already exists
    at /app/dist/database/migrate.js:104:27
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /app/dist/database/migrate.js:149:28
    ... 2 lines matching cause stack trace ...
    at async /app/dist/server.js:23:9 {
  cause: Error: An error occurred running 'storage-schema'. Rolled back this migration. No further migrations were run. Reason: role "anon" already exists
      at /app/node_modules/postgres-migrations/dist/run-migration.js:36:15
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async /app/dist/database/migrate.js:98:32
      at async /app/dist/database/migrate.js:149:28
      at async connectAndMigrate (/app/dist/database/migrate.js:48:9)
      at async runMigrationsOnTenant (/app/dist/database/migrate.js:35:5)
      at async /app/dist/server.js:23:9
}

Node.js v18.19.0
/app/dist/database/migrate.js:104
            const error = new Error(`Migration failed. Reason: ${e.message}`);
                          ^

Error: Migration failed. Reason: An error occurred running 'storage-schema'. Rolled back this migration. No further migrations were run. Reason: role "anon" already exists
    at /app/dist/database/migrate.js:104:27
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /app/dist/database/migrate.js:149:28
    ... 2 lines matching cause stack trace ...
    at async /app/dist/server.js:23:9 {
  cause: Error: An error occurred running 'storage-schema'. Rolled back this migration. No further migrations were run. Reason: role "anon" already exists
      at /app/node_modules/postgres-migrations/dist/run-migration.js:36:15
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async /app/dist/database/migrate.js:98:32
      at async /app/dist/database/migrate.js:149:28
      at async connectAndMigrate (/app/dist/database/migrate.js:48:9)
      at async runMigrationsOnTenant (/app/dist/database/migrate.js:35:5)
      at async /app/dist/server.js:23:9
}

Node.js v18.19.0
/app/dist/database/migrate.js:104
            const error = new Error(`Migration failed. Reason: ${e.message}`);
                          ^

Error: Migration failed. Reason: An error occurred running 'storage-schema'. Rolled back this migration. No further migrations were run. Reason: role "anon" already exists
    at /app/dist/database/migrate.js:104:27
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /app/dist/database/migrate.js:149:28
    ... 2 lines matching cause stack trace ...
    at async /app/dist/server.js:23:9 {
  cause: Error: An error occurred running 'storage-schema'. Rolled back this migration. No further migrations were run. Reason: role "anon" already exists
      at /app/node_modules/postgres-migrations/dist/run-migration.js:36:15
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async /app/dist/database/migrate.js:98:32
      at async /app/dist/database/migrate.js:149:28
      at async connectAndMigrate (/app/dist/database/migrate.js:48:9)
      at async runMigrationsOnTenant (/app/dist/database/migrate.js:35:5)
      at async /app/dist/server.js:23:9
}

Node.js v18.19.0
/app/dist/database/migrate.js:104
            const error = new Error(`Migration failed. Reason: ${e.message}`);
                          ^

Error: Migration failed. Reason: An error occurred running 'storage-schema'. Rolled back this migration. No further migrations were run. Reason: role "anon" already exists
    at /app/dist/database/migrate.js:104:27
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /app/dist/database/migrate.js:149:28
    ... 2 lines matching cause stack trace ...
    at async /app/dist/server.js:23:9 {
  cause: Error: An error occurred running 'storage-schema'. Rolled back this migration. No further migrations were run. Reason: role "anon" already exists
      at /app/node_modules/postgres-migrations/dist/run-migration.js:36:15
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async /app/dist/database/migrate.js:98:32
      at async /app/dist/database/migrate.js:149:28
      at async connectAndMigrate (/app/dist/database/migrate.js:48:9)
      at async runMigrationsOnTenant (/app/dist/database/migrate.js:35:5)
      at async /app/dist/server.js:23:9
}

Node.js v18.19.0
/app/dist/database/migrate.js:104
            const error = new Error(`Migration failed. Reason: ${e.message}`);
                          ^

Error: Migration failed. Reason: An error occurred running 'storage-schema'. Rolled back this migration. No further migrations were run. Reason: role "anon" already exists
    at /app/dist/database/migrate.js:104:27
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /app/dist/database/migrate.js:149:28
    ... 2 lines matching cause stack trace ...
    at async /app/dist/server.js:23:9 {
  cause: Error: An error occurred running 'storage-schema'. Rolled back this migration. No further migrations were run. Reason: role "anon" already exists
      at /app/node_modules/postgres-migrations/dist/run-migration.js:36:15
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async /app/dist/database/migrate.js:98:32
      at async /app/dist/database/migrate.js:149:28
      at async connectAndMigrate (/app/dist/database/migrate.js:48:9)
      at async runMigrationsOnTenant (/app/dist/database/migrate.js:35:5)
      at async /app/dist/server.js:23:9
}

Node.js v18.19.0
/app/dist/database/migrate.js:104
            const error = new Error(`Migration failed. Reason: ${e.message}`);
                          ^

Error: Migration failed. Reason: An error occurred running 'storage-schema'. Rolled back this migration. No further migrations were run. Reason: role "anon" already exists
    at /app/dist/database/migrate.js:104:27
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /app/dist/database/migrate.js:149:28
    ... 2 lines matching cause stack trace ...
    at async /app/dist/server.js:23:9 {
  cause: Error: An error occurred running 'storage-schema'. Rolled back this migration. No further migrations were run. Reason: role "anon" already exists
      at /app/node_modules/postgres-migrations/dist/run-migration.js:36:15
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async /app/dist/database/migrate.js:98:32
      at async /app/dist/database/migrate.js:149:28
      at async connectAndMigrate (/app/dist/database/migrate.js:48:9)
      at async runMigrationsOnTenant (/app/dist/database/migrate.js:35:5)
      at async /app/dist/server.js:23:9
}

Node.js v18.19.0
/app/dist/database/migrate.js:104
            const error = new Error(`Migration failed. Reason: ${e.message}`);
                          ^

Error: Migration failed. Reason: An error occurred running 'storage-schema'. Rolled back this migration. No further migrations were run. Reason: role "anon" already exists
    at /app/dist/database/migrate.js:104:27
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /app/dist/database/migrate.js:149:28
    ... 2 lines matching cause stack trace ...
    at async /app/dist/server.js:23:9 {
  cause: Error: An error occurred running 'storage-schema'. Rolled back this migration. No further migrations were run. Reason: role "anon" already exists
      at /app/node_modules/postgres-migrations/dist/run-migration.js:36:15
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async /app/dist/database/migrate.js:98:32
      at async /app/dist/database/migrate.js:149:28
      at async connectAndMigrate (/app/dist/database/migrate.js:48:9)
      at async runMigrationsOnTenant (/app/dist/database/migrate.js:35:5)
      at async /app/dist/server.js:23:9
}

Node.js v18.19.0
service not healthy: [supabase_storage_xyz]
Try rerunning the command with --debug to troubleshoot the error.
```

**Comment by brnhynh** [comment]
> I can confirm there is an incompatibility with the latest version of storage which starts managing roles in a non-idempotent way https://github.com/supabase/storage/blame/master/migrations/tenant/0002-storage-schema.sql#L21.
> 
> The temporary workaround is to revert to an old version of storage by `rm supabase/.temp/storage-version`.
> 
> I will also make a patch release after discussing with the storage team on what's the intended behaviour.

Thanks for the temporary workaround! @sweatybridge

**Comment by martijnvanderpol** [comment]
Hey! Thanks for figuring it out. It seems to have solved the specific error I mentioned earlier. However, I'm now encountering a new error. After removing the .temp folder, re-linking with my remote project, and running `npx supabase start` again, this issue surfaced. I did update to CLI version **1.136.3**.

New error log:

```
realtime-dev.supabase_realtime_studio-on-tour-2024 container logs:
08:55:40.926 [error] Could not create schema migrations table. This error usually happens due to the following:

  * The database does not exist
  * The "schema_migrations" table, which Ecto uses for managing
    migrations, was defined by another library
  * There is a deadlock while migrating (such as using concurrent
    indexes with a migration_lock)

To fix the first issue, run "mix ecto.create".

To address the second, you can run "mix ecto.drop" followed by
"mix ecto.create". Alternatively you may configure Ecto to use
another table and/or repository for managing migrations:

    config :realtime, Realtime.Repo,
      migration_source: "some_other_table_for_schema_migrations",
      migration_repo: AnotherRepoForSchemaMigrations

The full error report is shown below.

** (Postgrex.Error) ERROR 3F000 (invalid_schema_name) no schema has been selected to create in
    (ecto_sql 3.8.3) lib/ecto/adapters/sql.ex:932: Ecto.Adapters.SQL.raise_sql_call_error/1
    (elixir 1.14.3) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (ecto_sql 3.8.3) lib/ecto/adapters/sql.ex:1024: Ecto.Adapters.SQL.execute_ddl/4
    (ecto_sql 3.8.3) lib/ecto/migrator.ex:696: Ecto.Migrator.verbose_schema_migration/3
    (ecto_sql 3.8.3) lib/ecto/migrator.ex:510: Ecto.Migrator.lock_for_migrations/4
    (ecto_sql 3.8.3) lib/ecto/migrator.ex:422: Ecto.Migrator.run/4
    (ecto_sql 3.8.3) lib/ecto/migrator.ex:146: Ecto.Migrator.with_repo/3
    nofile:1: (file)
```

Output of `npx supabase services`:

| SERVICE IMAGE           | LOCAL                | LINKED     |
|-------------------------|----------------------|------------|
| supabase/postgres       | 15.1.0.49            | 15.1.0.49  |
| supabase/gotrue         | v2.132.3             | v2.132.3   |
| postgrest/postgrest     | v10.2.0              | v10.2.0    |
| supabase/realtime       | v2.25.50             | -          |
| supabase/storage-api    | v0.46.3              | v0.46.3    |
| supabase/edge-runtime   | v1.32.0              | -          |
| supabase/studio         | 20240101-8e4a094     | -          |
| supabase/postgres-meta  | v0.75.0              | -          |
| supabase/logflare       | 1.4.0                | -          |
| bitnami/pgbouncer       | 1.20.1-debian-11-r39 | -          |
| darthsim/imgproxy       | v3.8.0               | -          |

**Comment by sweatybridge** [comment]
There's likely a conflict with this version of postgres image with realtime migrations. One way to fix it is to delete `supabase/.temp/postgres-version` file so it uses the latest pinned version. I will also make a patch to cli to ignore these incompatible versions.

Alternatively you may want to update your hosted project to the latest postgres version.

**Comment by sweatybridge** [comment]
So the earliest version of pg15 that is compatible with cli for local development is `15.1.0.55`. I've updated the beta release of cli to ignore versions before that. You can try it out with

```
npx supabase@beta start
```

**Comment by martijnvanderpol** [comment]
Great! That did the trick for me, even without upgrading the remote Postgres version to v15. I'll do that later. Thanks so much for your quick actions, @sweatybridge!

**Comment by mosnicholas** [comment]
@sweatybridge -- also running into these issues, but I don't have any local file called `supabase/.temp/postgres-version`. Instead, I just keep seeing these errors:

```
2024-01-29 19:58:46 2024-01-30 00:58:46.773 GMT [10] LOG:  could not open configuration file "/etc/postgresql-custom/read-replica.conf": No such file or directory
2024-01-29 19:58:46 2024-01-30 00:58:46.774 GMT [10] FATAL:  configuration file "/etc/postgresql/postgresql.conf" contains errors
2024-01-29 19:58:48 2024-01-30 00:58:48.535 GMT [10] LOG:  could not open configuration file "/etc/postgresql-custom/read-replica.conf": No such file or directory
2024-01-29 19:58:48 2024-01-30 00:58:48.535 GMT [10] FATAL:  configuration file "/etc/postgresql/postgresql.conf" contains errors
2024-01-29 19:58:51 2024-01-30 00:58:51.900 GMT [10] LOG:  could not open configuration file "/etc/postgresql-custom/read-replica.conf": No such file or directory
2024-01-29 19:58:51 2024-01-30 00:58:51.900 GMT [10] FATAL:  configuration file "/etc/postgresql/postgresql.conf" contains errors
2024-01-29 19:58:58 2024-01-30 00:58:58.457 GMT [10] LOG:  could not open configuration file "/etc/postgresql-custom/read-replica.conf": No such file or directory
2024-01-29 19:58:58 2024-01-30 00:58:58.457 GMT [10] FATAL:  configuration file "/etc/postgresql/postgresql.conf" contains errors
2024-01-29 19:59:11 2024-01-30 00:59:11.404 GMT [10] LOG:  could not open configuration file "/etc/postgresql-custom/read-replica.conf": No such file or directory
2024-01-29 19:59:11 2024-01-30 00:59:11.404 GMT [10] FATAL:  configuration file "/etc/postgresql/postgresql.conf" contains errors
```

Until I comment out the line importing that file in `/etc/postgresql/postgresql.conf`

**Comment by sweatybridge** [comment]
That's a separate error tracked here https://github.com/supabase/cli/issues/1892

**Comment by NeverioDev** [comment]
Hello mine worked after doing these steps
1. supabase link
2. supabase start

just did supabase link before doing supabase start

**Comment by mitjakukovec** [comment]
> Hello mine worked after doing these steps
> 
> 1. supabase link
> 2. supabase start
> 
> just did supabase link before doing supabase start

This was the solution for me!
