### ISSUE TITLE
supabase db reset fails with storage-schema issues: role "anon" already exists

### ISSUE THREAD

**Issue by ahmetsevki** [supabase/cli#1878]
**Describe the bug**
I created a custom schema called "consultant"
supabase init
supabase link
supabase db pull
supabase db pull --schema consultant

Error: Migration failed. Reason: An error occurred running 'storage-schema'. Rolled back this migration. No further migrations were run. Reason: role "anon" already exists

Tried to do:
supabase db reset

same error

then tried `supabase db reset`. It errors

**To Reproduce**
empty database

**Expected behavior**
It should restart the local database?

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS
 - Browser (if applicable) [e.g. chrome, safari]
 - Version of CLI [e.g. v1.60.0] 1.136.2
 - Version of supabase-js (if applicable) [e.g. v2.22.0]
 - Version of Node.js (if applicable) [e.g. v16.20.0]

**Additional context**
crashreport: 17d5083210934c43aae1588b51aceade

////////
Resetting local database...
Recreating database...
Setting up initial schema...
/app/dist/database/migrate.js:104
            const error = new Error(`Migration failed. Reason: ${e.message}`);
                          ^

Error: Migration failed. Reason: An error occurred running 'storage-schema'. Rolled back this migration. No further migrations were run. Reason: role "anon" already exists
    at /app/dist/database/migrate.js:104:27
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /app/dist/database/migrate.js:149:28
    ... 2 lines matching cause stack trace ...
    at async /app/dist/scripts/migrate-call.js:10:5 {
  cause: Error: An error occurred running 'storage-schema'. Rolled back this migration. No further migrations were run. Reason: role "anon" already exists
      at /app/node_modules/postgres-migrations/dist/run-migration.js:36:15
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async /app/dist/database/migrate.js:98:32
      at async /app/dist/database/migrate.js:149:28
      at async connectAndMigrate (/app/dist/database/migrate.js:48:9)
      at async runMigrationsOnTenant (/app/dist/database/migrate.js:35:5)
      at async /app/dist/scripts/migrate-call.js:10:5
}

Node.js v18.19.0
error running container: exit 1
Try rerunning the command with --debug to troubleshoot the error.
Sent crash report: 17d5083210934c43aae1588b51aceade
Quote the crash ID above when filing a bug report: https://github.com/supabase/cli/issues/new/choose

**Comment by brnhynh** [comment]
We're having this issue after updating Supabase CLI (version 1.136.2) and running `supabase start`. Here are the outputs:

```
supabase start
1.4.0: Pulling from supabase/logflare
261da4162673: Pull complete 
7d2a960092ca: Pull complete 
cab6fd4eb5d1: Pull complete 
05267fd6f742: Pull complete 
1e3eeb829493: Pull complete 
4cc5b43cfbf9: Pull complete 
455249722616: Pull complete 
4f4fb700ef54: Pull complete 
105209f6e8d8: Pull complete 
Digest: sha256:e693c787ffe1ae17b6e4e920a3cdd212416d3e1f97e1bd7cb5b67de0abbb0264
Status: Downloaded newer image for public.ecr.aws/supabase/logflare:1.4.0
2.8.1: Pulling from supabase/kong
9b18e9b68314: Pull complete 
7fd91e922960: Pull complete 
450997ae687c: Pull complete 
d8380bfcbd9b: Pull complete 
Digest: sha256:1b53405d8680a09d6f44494b7990bf7da2ea43f84a258c59717d4539abf09f6d
Status: Downloaded newer image for public.ecr.aws/supabase/kong:2.8.1
v2.132.3: Pulling from supabase/gotrue
b8180c93b172: Pull complete 
896f7a45b28c: Pull complete 
f601026daa99: Pull complete 
3fd170a1e9e8: Pull complete 
6e3acd8bfe40: Pull complete 
61462962e623: Pull complete 
Digest: sha256:1bfae25acead513fbd459679a08463a1fc679769e6586c773cfc32d26c5b6dcf
Status: Downloaded newer image for public.ecr.aws/supabase/gotrue:v2.132.3
3.0.3: Pulling from supabase/inbucket
f97344484467: Pull complete 
c93cd632d565: Pull complete 
7cadd1efbbe6: Pull complete 
9853c0941218: Pull complete 
b6f6817b1d4a: Pull complete 
c5c956c4e9fc: Pull complete 
59cbfb43403a: Pull complete 
9c842edb6049: Pull complete 
Digest: sha256:dc912ab76de647ca2a363fe285515e512e964cf699166773f3c2c73f5e7f71c0
Status: Downloaded newer image for public.ecr.aws/supabase/inbucket:3.0.3
v2.25.50: Pulling from supabase/realtime
66dbba0fb1b5: Pull complete 
4166bd72e87a: Pull complete 
5dd8dfaab4d9: Pull complete 
07484305c37f: Pull complete 
a29e87bf71ee: Pull complete 
933c3bd59c23: Pull complete 
9614f9b82227: Pull complete 
3031aaa00e8d: Pull complete 
2faab5f119c5: Pull complete 
f54398b16e61: Pull complete 
2ffe6f08fe84: Pull complete 
0aa8ae17bf21: Pull complete 
Digest: sha256:c54ae830834a0a31587c22045a6e6c6743b5f9335527a179681bef34ca03260b
Status: Downloaded newer image for public.ecr.aws/supabase/realtime:v2.25.50
v12.0.2: Pulling from supabase/postgrest
d519a3a2a796: Already exists 
4e0059d9a247: Pull complete 
1ed0fb2de4f4: Pull complete 
Digest: sha256:79369c0cdf9d7112ed4e327bc1b80156be11575dd66fbda245077a2d13b803bc
Status: Downloaded newer image for public.ecr.aws/supabase/postgrest:v12.0.2
v3.8.0: Pulling from supabase/imgproxy
df8e44b0463f: Pull complete 
b0f1dd53d7c3: Pull complete 
ead8ac122bf1: Pull complete 
4667765ff03a: Pull complete 
744485a3a3a9: Pull complete 
8650da0c91b5: Pull complete 
Digest: sha256:0facd355d50f3be665ebe674486f2b2e9cdaebd3f74404acd9b7fece2f661435
Status: Downloaded newer image for public.ecr.aws/supabase/imgproxy:v3.8.0
v1.32.0: Pulling from supabase/edge-runtime
a5573528b1f0: Pull complete 
634d09a65844: Pull complete 
4f5c02c75ddc: Pull complete 
8b21a364ecf7: Pull complete 
Digest: sha256:fa4e2d1e0477913f372fcaf7f01dbfbcde470f07b9957057756b0e1327509b20
Status: Downloaded newer image for public.ecr.aws/supabase/edge-runtime:v1.32.0
v0.75.0: Pulling from supabase/postgres-meta
2c6d21737d83: Pull complete 
2398be8db5f7: Pull complete 
a8aaaf4c9c12: Pull complete 
b2640ab71335: Pull complete 
8f5ae29d9d42: Pull complete 
0f1f70e3581e: Pull complete 
1b05712d5904: Pull complete 
a7e8636ebe6f: Pull complete 
de9796f4c8ce: Pull complete 
Digest: sha256:c5042d12dbf0366a6e27dafb2bb1f2c0d61662da7fb8e065ab51b6c15a964145
Status: Downloaded newer image for public.ecr.aws/supabase/postgres-meta:v0.75.0
20240101-8e4a094: Pulling from supabase/studio
24e221e92a36: Pull complete 
dbc596c5cca5: Pull complete 
b665ed4ee4f7: Pull complete 
392ddf2ad556: Pull complete 
cb3d1a19897b: Pull complete 
bcec8420c1a9: Pull complete 
684c2e9fdfb4: Pull complete 
eec526392e29: Pull complete 
7847b6d22acf: Pull complete 
b5ae73a7697d: Pull complete 
Digest: sha256:305ffb3c0e8aa72bcdca451895b88a7ed11f613ebbaf22cd5086e6a94ef73b01
Status: Downloaded newer image for public.ecr.aws/supabase/studio:20240101-8e4a094
supabase_storage_xyz container logs:
/app/dist/database/migrate.js:104
            const error = new Error(`Migration failed. Reason: ${e.message}`);
                          ^

Error: Migration failed. Reason: An error occurred running 'storage-schema'. Rolled back this migration. No further migrations were run. Reason: role "anon" already exists
    at /app/dist/database/migrate.js:104:27
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /app/dist/database/migrate.js:149:28
    ... 2 lines matching cause stack trace ...
    at async /app/dist/server.js:23:9 {
  cause: Error: An error occurred running 'storage-schema'. Rolled back this migration. No further migrations were run. Reason: role "anon" already exists
      at /app/node_modules/postgres-migrations/dist/run-migration.js:36:15
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async /app/dist/database/migrate.js:98:32
      at async /app/dist/database/migrate.js:149:28
      at async connectAndMigrate (/app/dist/database/migrate.js:48:9)
      at async runMigrationsOnTenant (/app/dist/database/migrate.js:35:5)
      at async /app/dist/server.js:23:9
}

Node.js v18.19.0
/app/dist/database/migrate.js:104
            const error = new Error(`Migration failed. Reason: ${e.message}`);
                          ^

Error: Migration failed. Reason: An error occurred running 'storage-schema'. Rolled back this migration. No further migrations were run. Reason: role "anon" already exists
    at /app/dist/database/migrate.js:104:27
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /app/dist/database/migrate.js:149:28
    ... 2 lines matching cause stack trace ...
    at async /app/dist/server.js:23:9 {
  cause: Error: An error occurred running 'storage-schema'. Rolled back this migration. No further migrations were run. Reason: role "anon" already exists
      at /app/node_modules/postgres-migrations/dist/run-migration.js:36:15
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async /app/dist/database/migrate.js:98:32
      at async /app/dist/database/migrate.js:149:28
      at async connectAndMigrate (/app/dist/database/migrate.js:48:9)
      at async runMigrationsOnTenant (/app/dist/database/migrate.js:35:5)
      at async /app/dist/server.js:23:9
}

Node.js v18.19.0
/app/dist/database/migrate.js:104
            const error = new Error(`Migration failed. Reason: ${e.message}`);
                          ^

Error: Migration failed. Reason: An error occurred running 'storage-schema'. Rolled back this migration. No further migrations were run. Reason: role "anon" already exists
    at /app/dist/database/migrate.js:104:27
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /app/dist/database/migrate.js:149:28
    ... 2 lines matching cause stack trace ...
    at async /app/dist/server.js:23:9 {
  cause: Error: An error occurred running 'storage-schema'. Rolled back this migration. No further migrations were run. Reason: role "anon" already exists
      at /app/node_modules/postgres-migrations/dist/run-migration.js:36:15
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async /app/dist/database/migrate.js:98:32
      at async /app/dist/database/migrate.js:149:28
      at async connectAndMigrate (/app/dist/database/migrate.js:48:9)
      at async runMigrationsOnTenant (/app/dist/database/migrate.js:35:5)
      at async /app/dist/server.js:23:9
}

Node.js v18.19.0
/app/dist/database/migrate.js:104
            const error = new Error(`Migration failed. Reason: ${e.message}`);
                          ^

Error: Migration failed. Reason: An error occurred running 'storage-schema'. Rolled back this migration. No further migrations were run. Reason: role "anon" already exists
    at /app/dist/database/migrate.js:104:27
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /app/dist/database/migrate.js:149:28
    ... 2 lines matching cause stack trace ...
    at async /app/dist/server.js:23:9 {
  cause: Error: An error occurred running 'storage-schema'. Rolled back this migration. No further migrations were run. Reason: role "anon" already exists
      at /app/node_modules/postgres-migrations/dist/run-migration.js:36:15
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async /app/dist/database/migrate.js:98:32
      at async /app/dist/database/migrate.js:149:28
      at async connectAndMigrate (/app/dist/database/migrate.js:48:9)
      at async runMigrationsOnTenant (/app/dist/database/migrate.js:35:5)
      at async /app/dist/server.js:23:9
}

Node.js v18.19.0
/app/dist/database/migrate.js:104
            const error = new Error(`Migration failed. Reason: ${e.message}`);
                          ^

Error: Migration failed. Reason: An error occurred running 'storage-schema'. Rolled back this migration. No further migrations were run. Reason: role "anon" already exists
    at /app/dist/database/migrate.js:104:27
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /app/dist/database/migrate.js:149:28
    ... 2 lines matching cause stack trace ...
    at async /app/dist/server.js:23:9 {
  cause: Error: An error occurred running 'storage-schema'. Rolled back this migration. No further migrations were run. Reason: role "anon" already exists
      at /app/node_modules/postgres-migrations/dist/run-migration.js:36:15
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async /app/dist/database/migrate.js:98:32
      at async /app/dist/database/migrate.js:149:28
      at async connectAndMigrate (/app/dist/database/migrate.js:48:9)
      at async runMigrationsOnTenant (/app/dist/database/migrate.js:35:5)
      at async /app/dist/server.js:23:9
}

Node.js v18.19.0
/app/dist/database/migrate.js:104
            const error = new Error(`Migration failed. Reason: ${e.message}`);
                          ^

Error: Migration failed. Reason: An error occurred running 'storage-schema'. Rolled back this migration. No further migrations were run. Reason: role "anon" already exists
    at /app/dist/database/migrate.js:104:27
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /app/dist/database/migrate.js:149:28
    ... 2 lines matching cause stack trace ...
    at async /app/dist/server.js:23:9 {
  cause: Error: An error occurred running 'storage-schema'. Rolled back this migration. No further migrations were run. Reason: role "anon" already exists
      at /app/node_modules/postgres-migrations/dist/run-migration.js:36:15
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async /app/dist/database/migrate.js:98:32
      at async /app/dist/database/migrate.js:149:28
      at async connectAndMigrate (/app/dist/database/migrate.js:48:9)
      at async runMigrationsOnTenant (/app/dist/database/migrate.js:35:5)
      at async /app/dist/server.js:23:9
}

Node.js v18.19.0
/app/dist/database/migrate.js:104
            const error = new Error(`Migration failed. Reason: ${e.message}`);
                          ^

Error: Migration failed. Reason: An error occurred running 'storage-schema'. Rolled back this migration. No further migrations were run. Reason: role "anon" already exists
    at /app/dist/database/migrate.js:104:27
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /app/dist/database/migrate.js:149:28
    ... 2 lines matching cause stack trace ...
    at async /app/dist/server.js:23:9 {
  cause: Error: An error occurred running 'storage-schema'. Rolled back this migration. No further migrations were run. Reason: role "anon" already exists
      at /app/node_modules/postgres-migrations/dist/run-migration.js:36:15
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async /app/dist/database/migrate.js:98:32
      at async /app/dist/database/migrate.js:149:28
      at async connectAndMigrate (/app/dist/database/migrate.js:48:9)
      at async runMigrationsOnTenant (/app/dist/database/migrate.js:35:5)
      at async /app/dist/server.js:23:9
}

Node.js v18.19.0
/app/dist/database/migrate.js:104
            const error = new Error(`Migration failed. Reason: ${e.message}`);
                          ^

Error: Migration failed. Reason: An error occurred running 'storage-schema'. Rolled back this migration. No further migrations were run. Reason: role "anon" already exists
    at /app/dist/database/migrate.js:104:27
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /app/dist/database/migrate.js:149:28
    ... 2 lines matching cause stack trace ...
    at async /app/dist/server.js:23:9 {
  cause: Error: An error occurred running 'storage-schema'. Rolled back this migration. No further migrations were run. Reason: role "anon" already exists
      at /app/node_modules/postgres-migrations/dist/run-migration.js:36:15
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async /app/dist/database/migrate.js:98:32
      at async /app/dist/database/migrate.js:149:28
      at async connectAndMigrate (/app/dist/database/migrate.js:48:9)
      at async runMigrationsOnTenant (/app/dist/database/migrate.js:35:5)
      at async /app/dist/server.js:23:9
}

Node.js v18.19.0
/app/dist/database/migrate.js:104
            const error = new Error(`Migration failed. Reason: ${e.message}`);
                          ^

Error: Migration failed. Reason: An error occurred running 'storage-schema'. Rolled back this migration. No further migrations were run. Reason: role "anon" already exists
    at /app/dist/database/migrate.js:104:27
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /app/dist/database/migrate.js:149:28
    ... 2 lines matching cause stack trace ...
    at async /app/dist/server.js:23:9 {
  cause: Error: An error occurred running 'storage-schema'. Rolled back this migration. No further migrations were run. Reason: role "anon" already exists
      at /app/node_modules/postgres-migrations/dist/run-migration.js:36:15
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async /app/dist/database/migrate.js:98:32
      at async /app/dist/database/migrate.js:149:28
      at async connectAndMigrate (/app/dist/database/migrate.js:48:9)
      at async runMigrationsOnTenant (/app/dist/database/migrate.js:35:5)
      at async /app/dist/server.js:23:9
}

Node.js v18.19.0
service not healthy: [supabase_storage_xyz]
Try rerunning the command with --debug to troubleshoot the error.
```

**Comment by sweatybridge** [comment]
The root cause is the same as https://github.com/supabase/cli/issues/1877#issuecomment-1909291915

Could you try the workaround there for now?
