### ISSUE TITLE
After update to 1.203.3 containers won't start due to missing FILE_STORAGE_BACKEND_PATH env variable

### ISSUE THREAD

**Issue by evelant** [supabase/cli#2738]
**Describe the bug**
After update to 1.203.3 containers won't start due to missing FILE_STORAGE_BACKEND_PATH env variable

**To Reproduce**
1. Update from an earlier version to 1.203.3 (I updated from 1.200.3)

**Expected behavior**
Updates to supabase cli should always automatically make any required configuration changes and/or inform the user of changes that need to be made.

**Screenshots**
n/a

**System information**
Rerun the failing command with `--create-ticket` flag.
 - Ticket ID: 54f47e6178024986997f6846cec52bdc
 - Version of OS: macos 14.6.1
 - Version of CLI: 1.203.3
 - Version of Docker: 
 - Versions of services:
 ```
        SERVICE IMAGE      │      LOCAL       │   LINKED
  ─────────────────────────┼──────────────────┼─────────────
    supabase/postgres      │ 15.6.1.116       │ 15.6.1.116
    supabase/gotrue        │ v2.162.1         │ -
    postgrest/postgrest    │ v12.2.3          │ -
    supabase/realtime      │ v2.30.34         │ -
    supabase/storage-api   │ v1.11.13         │ -
    supabase/edge-runtime  │ v1.58.11         │ -
    supabase/studio        │ 20240930-16f2b8e │ -
    supabase/postgres-meta │ v0.83.2          │ -
    supabase/logflare      │ 1.4.0            │ -
    supabase/supavisor     │ 1.1.56           │ -
```

**Additional context**

relevant --debug logs section
```
/app/dist/storage/backend/file.js:64
      throw new Error("FILE_STORAGE_BACKEND_PATH env variable not set");
      ^

Error: FILE_STORAGE_BACKEND_PATH env variable not set
    at new FileBackend (/app/dist/storage/backend/file.js:64:13)
    at createStorageBackend (/app/dist/storage/backend/index.js:35:22)
    at Object.<anonymous> (/app/dist/storage/events/base-event.js:36:64)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/app/dist/storage/events/webhook.js:34:25)
```

I see there is a variable for storage config `STORAGE_FILE_BACKEND_PATH` as opposed to `FILE_STORAGE_BACKEND_PATH` -- is this possibly just a typo bug in supabase-cli?

**Comment by sos0** [comment]
This happens prior to update as well, on 1.19x
