### ISSUE TITLE
Migration issue with supabase db diff for partition tables

### ISSUE THREAD

**Issue by HimaniShah1** [supabase/cli#2970]
**Describe the bug**
supabase db diff command gives an error when creating a migration on db that contains partition table. A new partition table is generated every month and for incremental migrations, it is creating an issue.

**To Reproduce**
1. Create a db with partition table
2. dump it and create the first migration
3. create another table in that partition table
4. run supabase db diff (to create a new migration)

**Expected behavior**
A new migration file with the updated changes should be created.

**System information**
 - Version of CLI: Tried with both v1.226.4 and v2.0.0
 - Version of Docker: v27.3.1

**Error Log**
error diffing schema: error running container: exit 1:                                                     
Traceback (most recent call last):                                                                         
  File "/usr/local/bin/migra", line 8, in <module>                                                         
    sys.exit(do_command())                                                                                 
  File "/usr/local/lib/python3.9/site-packages/migra/command.py", line 121, in do_command                  
    status = run(args)                                                                                     
  File "/usr/local/lib/python3.9/site-packages/migra/command.py", line 98, in run                          
    m.add_all_changes(privileges=args.with_privileges)                                                     
  File "/usr/local/lib/python3.9/site-packages/migra/migra.py", line 107, in add_all_changes               
    self.add(self.changes.tables_only_selectables())                                                       
  File "/usr/local/lib/python3.9/site-packages/migra/changes.py", line 496, in get_selectable_changes      
    statements += get_table_changes(                                                                       
  File "/usr/local/lib/python3.9/site-packages/migra/changes.py", line 233, in get_table_changes           
    rls_alter = v.alter_rls_statement                                                                      
  File "/usr/local/lib/python3.9/site-packages/schemainspect/pg/obj.py", line 228, in alter_rls_statement  
    return self.alter_table_statement(self.alter_rls_clause)                                               
  File "/usr/local/lib/python3.9/site-packages/schemainspect/pg/obj.py", line 145, in alter_table_statement
    raise NotImplementedError  # pragma: no cover                                                          
NotImplementedError

**Additional context**
Seems like migra tool is creating an issue on policies. But happening only with partition table. It works fine if the tables are not partitioned.

**Comment by ProjectINT** [comment]
https://github.com/supabase/cli/issues/4562 - also have this problem

**Comment by ProjectINT** [comment]
@HimaniShah1 Do you solve this problem? I have similar

**Comment by quick691fr** [comment]
I do have the same issue, using also partitioned tables :

`
error diffing schema: error running container: exit 1:
Error: Not implemented
    at InspectedSelectable.alter_table_statement (file:///var/tmp/sb-compile-edge-runtime/node_modules/localhost/@pgkit/schemainspect/0.6.1/dist/pg/obj.js:212:15)
    at InspectedSelectable.get alter_rls_statement (file:///var/tmp/sb-compile-edge-runtime/node_modules/localhost/@pgkit/schemainspect/0.6.1/dist/pg/obj.js:275:21)
    at get_table_changes (file:///var/tmp/sb-compile-edge-runtime/node_modules/localhost/@pgkit/migra/0.6.1/dist/changes.js:244:33)
    at get_selectable_changes (file:///var/tmp/sb-compile-edge-runtime/node_modules/localhost/@pgkit/migra/0.6.1/dist/changes.js:449:40)
    at Changes.<anonymous> (file:///var/tmp/sb-compile-edge-runtime/node_modules/localhost/@pgkit/migra/0.6.1/dist/changes.js:506:20)
    at Migration.add_all_changes (file:///var/tmp/sb-compile-edge-runtime/node_modules/localhost/@pgkit/migra/0.6.1/dist/migra.js:83:31)
    at file:///var/tmp/sb-compile-edge-runtime/index.ts:103:7
    at eventLoopTick (ext:core/01_core.js:175:7)
main worker has been destroyed
`
Version of CLI: 2.84.2

@7ttp any news on that ?
