### ISSUE TITLE
Error in eszip wasm with lastest CLI (1.14.2)

### ISSUE THREAD

**Issue by rlightner** [supabase/cli#621]
Updated to latest CLI with no change in functions. Trying to deploy a text change to a function and getting this error now:
```cmd
Error: Error bundling function: exit status 1
file:///src/index.ts
file:///_utils/cors.ts
file:///_utils/stripe.ts
file:///_utils/supabase.ts
file:///_utils/db_types.ts
error: Uncaught (in promise) Error: Relative import path "http" not prefixed with / or ./ or ../
      const ret = new Error(getStringFromWasm0(arg0, arg1));
                  ^
    at __wbg_new_8d2af00bc1e329ee (https://deno.land/x/eszip@v0.30.0/eszip_wasm.generated.js:312:19)
    at <anonymous> (https://deno.land/x/eszip@v0.30.0/eszip_wasm_bg.wasm:1:79439)
    at <anonymous> (https://deno.land/x/eszip@v0.30.0/eszip_wasm_bg.wasm:1:1388039)
    at <anonymous> (https://deno.land/x/eszip@v0.30.0/eszip_wasm_bg.wasm:1:1862894)
    at __wbg_adapter_18 (https://deno.land/x/eszip@v0.30.0/eszip_wasm.generated.js:146:6)
    at real (https://deno.land/x/eszip@v0.30.0/eszip_wasm.generated.js:130:14)
```

**Comment by soedirgo** [comment]
Thanks for reporting, we're looking into this. In the meanwhile you can try running it like:

```sh
supabase functions deploy --legacy-bundle your-function
```

**Comment by rlightner** [comment]
I had a stripe reference not calling`&no-check` and that seemed to do the trick. Is that documented anywhere?  Thanks for unblocking me!

**Comment by soedirgo** [comment]
Happy to help! We recently made a change to the deploy command which might've caused this - will add a note for this on our docs :+1:
