### ISSUE TITLE
npx supabase start returning an error

### ISSUE THREAD

**Issue by fergusmeiklejohn** [supabase/cli#717]
# Bug report
`npx supabase ...` is not working

this is the log of the run:
```bash
0 verbose cli /usr/local/bin/node /usr/local/lib/node_modules/npm/bin/npm-cli.js
1 info using npm@8.15.0
2 info using node@v16.17.0
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 0ms
5 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:/Users/fergusmeiklejohn/dev/evesa-proj/evesa-dev/.npmrc Completed in 1ms
10 timing config:load:project Completed in 3ms
11 timing config:load:file:/Users/fergusmeiklejohn/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 1ms
17 timing config:load:setEnvs Completed in 0ms
18 timing config:load Completed in 7ms
19 timing npm:load:configload Completed in 7ms
20 timing npm:load:mkdirpcache Completed in 0ms
21 timing npm:load:mkdirplogs Completed in 0ms
22 verbose title npm exec supabase start
23 verbose argv "exec" "--" "supabase" "start"
24 timing npm:load:setTitle Completed in 5ms
25 timing config:load:flatten Completed in 1ms
26 timing npm:load:display Completed in 2ms
27 verbose logfile logs-max:10 dir:/Users/fergusmeiklejohn/.npm/_logs
28 verbose logfile /Users/fergusmeiklejohn/.npm/_logs/2022-12-19T01_35_19_463Z-debug-0.log
29 timing npm:load:logFile Completed in 2ms
30 timing npm:load:timers Completed in 0ms
31 timing npm:load:configScope Completed in 0ms
32 timing npm:load Completed in 17ms
33 silly logfile start cleaning logs, removing 1 files
34 timing arborist:ctor Completed in 0ms
35 silly logfile done cleaning log files
36 http fetch GET 200 https://registry.npmjs.org/supabase 965ms (cache revalidated)
37 timing command:exec Completed in 1586ms
38 verbose stack Error: could not determine executable to run
38 verbose stack     at getBinFromManifest (/usr/local/lib/node_modules/npm/node_modules/libnpmexec/lib/get-bin-from-manifest.js:17:23)
38 verbose stack     at exec (/usr/local/lib/node_modules/npm/node_modules/libnpmexec/lib/index.js:135:15)
38 verbose stack     at async module.exports (/usr/local/lib/node_modules/npm/lib/cli.js:78:5)
39 verbose pkgid supabase@1.26.9
40 verbose cwd /Users/fergusmeiklejohn/dev/evesa-proj/evesa-dev
41 verbose Darwin 22.2.0
42 verbose node v16.17.0
43 verbose npm  v8.15.0
44 error could not determine executable to run
45 verbose exit 1
46 timing npm Completed in 1637ms
47 verbose code 1
48 error A complete log of this run can be found in:
48 error     /Users/fergusmeiklejohn/.npm/_logs/2022-12-19T01_35_19_463Z-debug-0.log

```

## System information

- OS: macOS13
- Version of Node.js: 16.7.0

**Comment by sweatybridge** [comment]
Does this work for you on a fresh install of supabase cli? I tried the following commands but cannot reproduce

```bash
mkdir test-project
cd test-project
npm init -y
npm i --save-dev supabase
npx supabase --version
```

Perhaps try deleting `node_modules` and reinstalling?

**Comment by fergusmeiklejohn** [comment]
The failure is with `npx` I got around it by installing supabase locally which works for `supabase start` but creating types doesn't work

**Comment by sweatybridge** [comment]
Thanks for helping to debug this issue. It should be fixed now.
